In [2]:
import warnings
warnings.filterwarnings(action='ignore')
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

분석하기 좋은 데이터

분석하기 좋은 데이터는 데이터 집합을 분석하기 좋은 형태로 만들어 놓은 것을 말하고 데이터 분석 작업에서 데이터 정리는 아주 중요한 작업으로 실제 데이터 분석작업의 70% 이상을 차지하고 있는 작업이 데이터 정리(전처리) 작업이다.  
분석하기 좋은 데이터는 데이터를 분석 목적에 맞는 데이터를 모아서(수집) 새로운 표(table, 데이터프레임)를 만들어야 하고 측정한 값(데이터 1건)은 행으로 변수(특성, 속성)들을 열로 고성하며 이 모든 조건을 만족하는 데이터를 깔끔한 데이터(good data)라고 부른다.

In [3]:
df1 = pd.read_csv('./data/concat_1.csv')
df1

    A   B   C   D
0  a0  b0  c0  d0
1  a1  b1  c1  d1
2  a2  b2  c2  d2
3  a3  b3  c3  d3

In [4]:
df2 = pd.read_csv('./data/concat_2.csv')
df2

    A   B   C   D
0  a4  b4  c4  d4
1  a5  b5  c5  d5
2  a6  b6  c6  d6
3  a7  b7  c7  d7

In [5]:
df3 = pd.read_csv('./data/concat_3.csv')
df3

     A    B    C    D
0   a8   b8   c8   d8
1   a9   b9   c9   d9
2  a10  b10  c10  d10
3  a11  b11  c11  d11

concat() 메소드는 데이터프레임을 연결한다.  
연결하려는 데이터프레임을 리스트에 담아서 concat() 메소드에 전달하면 연결한 데이터프레임을 리턴한다.  
concat([데이터프레임1, 데이터프레임2, ...][, axis])  
axis 속성을 생략하면 0이 기본값이고 위에서 아래 방향으로 연결하고 axis=1로 지정하면 왼쪽에서 오른쪽 방향으로 연결한다.

In [7]:
row_concat = pd.concat([df1, df2, df3]) # pd.concat([df1, df2, df3], axis=0), 아래로 붙인다.
row_concat

     A    B    C    D
0   a0   b0   c0   d0
1   a1   b1   c1   d1
2   a2   b2   c2   d2
3   a3   b3   c3   d3
0   a4   b4   c4   d4
1   a5   b5   c5   d5
2   a6   b6   c6   d6
3   a7   b7   c7   d7
0   a8   b8   c8   d8
1   a9   b9   c9   d9
2  a10  b10  c10  d10
3  a11  b11  c11  d11

In [8]:
col_concat = pd.concat([df1, df2, df3], axis=1) # 옆으로 붙인다.
col_concat

    A   B   C   D   A   B   C   D    A    B    C    D
0  a0  b0  c0  d0  a4  b4  c4  d4   a8   b8   c8   d8
1  a1  b1  c1  d1  a5  b5  c5  d5   a9   b9   c9   d9
2  a2  b2  c2  d2  a6  b6  c6  d6  a10  b10  c10  d10
3  a3  b3  c3  d3  a7  b7  c7  d7  a11  b11  c11  d11

데이터프레임에 데이터 1건을 추가하기

In [9]:
row_series = pd.Series(['n1', 'n2', 'n3', 'n4']) # 시리즈
row_series

0    n1
1    n2
2    n3
3    n4
dtype: str

In [11]:
# axis를 생략해서 axis=0인 상태에서 시리즈가 새로운 행으로 추가되지 않고 새로운 열로 추가된다.
# 시리즈에 열 이름이 없기때문에 시리즈를 데이터프레임에 새로운 행으로 추가하려 할 때 제대로 추가되지 않는다.
# 추가하는 시리즈를 새로운 열로 간주해서 0이라는 열이 추가된다.
pd.concat([df1, row_series])

     A    B    C    D    0
0   a0   b0   c0   d0  NaN
1   a1   b1   c1   d1  NaN
2   a2   b2   c2   d2  NaN
3   a3   b3   c3   d3  NaN
0  NaN  NaN  NaN  NaN   n1
1  NaN  NaN  NaN  NaN   n2
2  NaN  NaN  NaN  NaN   n3
3  NaN  NaN  NaN  NaN   n4

In [12]:
row_df = pd.DataFrame(['n1', 'n2', 'n3', 'n4']) # 열 방향 데이터프레임
row_df

    0
0  n1
1  n2
2  n3
3  n4

In [13]:
pd.concat([df1, row_df])

     A    B    C    D    0
0   a0   b0   c0   d0  NaN
1   a1   b1   c1   d1  NaN
2   a2   b2   c2   d2  NaN
3   a3   b3   c3   d3  NaN
0  NaN  NaN  NaN  NaN   n1
1  NaN  NaN  NaN  NaN   n2
2  NaN  NaN  NaN  NaN   n3
3  NaN  NaN  NaN  NaN   n4

DataFrame()의 인수로 ['n1', 'n2', 'n3', 'n4']와 같이 1차원 리스트를 전달하면 데이터 하나하나를 개별 데이터로 취급해서 열방향 데이터프레임이 생성된다.  
[['n1', 'n2', 'n3', 'n4']]와 같이 2차원 리스트로 전달하면 1차원 리스트 전체를 1개의 데이터로 취급해서 행 방향 데이터프레임이 생성된다.

In [14]:
row_df = pd.DataFrame([['n1', 'n2', 'n3', 'n4']]) # 행 방향 데이터프레임
row_df

    0   1   2   3
0  n1  n2  n3  n4

In [15]:
pd.concat([df1, row_df])

     A    B    C    D    0    1    2    3
0   a0   b0   c0   d0  NaN  NaN  NaN  NaN
1   a1   b1   c1   d1  NaN  NaN  NaN  NaN
2   a2   b2   c2   d2  NaN  NaN  NaN  NaN
3   a3   b3   c3   d3  NaN  NaN  NaN  NaN
0  NaN  NaN  NaN  NaN   n1   n2   n3   n4

DataFrame()으로 데이터프레임을 생성할 때 열 인덱스를 지정하지 않으면 pandas가 자동으로 0, 1, 2, 3, ...와 같은 방식으로 열 인덱스를 지정하기 때문에 columns 속성으로 열 인덱스를 전달한다.

In [16]:
# row_df = pd.DataFrame([['n1', 'n2', 'n3', 'n4']], columns=['A', 'B', 'C', 'D'])
row_df = pd.DataFrame([['n1', 'n2', 'n3', 'n4']], columns=df1.columns)
row_df

    A   B   C   D
0  n1  n2  n3  n4

In [17]:
pd.concat([df1, row_df])

    A   B   C   D
0  a0  b0  c0  d0
1  a1  b1  c1  d1
2  a2  b2  c2  d2
3  a3  b3  c3  d3
0  n1  n2  n3  n4