# 라이브러리 설치

In [1]:
# !pip install pyLDAvis
# !pip install tensorflow

In [2]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import koreanize_matplotlib
import seaborn as sns
import sklearn
sklearn.set_config(display='text')

# 분석 과정

120다산콜재단은 2007년 다산콜센터로 시작한 서울시의 행정 상담 민원 서비스로 365일 24시간 상담 서비스를 제공하고 있다. 다산콜재단의 질문과 답변 데이터를 사용한다.

## 분석 과정은 크게 다음 두 가지 순서로 진행한다.

① 120다산콜재단 데이터(seoul-120-text.csv)를 머신러닝 방법인 잠재 디리클레 할당을 통한 토픽별로 분석 시각화  
&nbsp;&nbsp;&nbsp;▶ pyLDAvis 라이브러리를 이용한 시각화  
&nbsp;&nbsp;&nbsp;▶ TF-IDF 잠재 디리클레 할당  
② 토픽 모델링으로 데이터를 토픽별로 분류한 뒤, 딥러닝 방법 중 하나인 순환 신경망(RNN) 모델인 LSTM 모델로 학습해서 분류한다.

먼저 `잠재 디리클레 할당(Latent Dirichlet Allocation, LDA)`을 통한 토픽 모델링(Topic Modeling)으로 분석하고, 토픽 모델링을 시각화해 주는 pyLDAvis 라이브러리를 이용해 시각화해 본다. 그리고 학습, 테스트 데이터를 분리해서 LSTM 모델을 만들어 학습시킨다.

# 잠재 디리클레 할당으로 토픽 분류하기

LDA는 주어진 문서에 대해 각 문서에 어떤 토픽(주제)들이 있는지 서술하는 확률적 토픽 분류 기법 중 하나이다. 미리 알고 있는 주제별 단어 수 분포를 바탕으로, 주어진 문서에서 발견된 단 수 분포를 분석함으로써 해당 문서가 어떤 주제들을 함께 다루고 있을지 예측한다.

<img src="./잠재디리클레할당그림.png" width="900" align="left" />

LDA는 문서에 대한 범주의 연관성을 찾는 데 사용하는 확률론적 모델이며, 다음 두 가지 확률값을 사용해 문서를 군집화 한다.

P(단어|주제): 특정 단어가 주제와 연관될 확률, 이 첫 번째 확률 집합은 워드 * 주제 행렬로 간주된다.  
P(주제|문서): 문서와 관련된 항목, 이 두 번째 확률 집합은 주제 * 문서 행렬로 간주된다.

확률값은 모든 단어, 주제 및 문서에 대해 계산된다.

## 데이터 불러오기

In [3]:
df = pd.read_csv('./data/seoul-120-text.csv')
df.shape

(2645, 5)

In [4]:
df.head()

,번호,분류,제목,내용,내용번호
0,2645,복지,아빠 육아휴직 장려금,아빠 육아휴직 장려금 업무개요 남성근로자의 육아휴직을 장려하고 양육에 따른 경...,23522464
1,2644,경제,[서울산업진흥원] 서울메이드란?,서울산업진흥원 서울메이드란 서울의 감성을 담은 다양하고 새로운 경험을 제공하기 위해...,23194045
2,2643,환경,(강북구) 정비중,강북구 정비중 업무개요 투명 폐트병을 교환보상하므로 수거율을 높이고 폐기물을 감...,23032485
3,2642,복지,"광진맘택시 운영(임산부,영아 양육가정 전용 택시)",광진맘택시 운영임산부영아 양육가정 전용 택시 업무개요 교통약자인 임산부와 영아가정...,22904492
4,2641,복지,마포 뇌병변장애인 비전센터,마포 뇌병변장애인 비전센터 마포뇌병변장애인 비전센터 운영 구분 내용 목적 학...,22477798

In [5]:
df.isnull().sum()

번호      0
분류      0
제목      0
내용      0
내용번호    0
dtype: int64

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2645 entries, 0 to 2644
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   번호      2645 non-null   int64
 1   분류      2645 non-null   str
 2   제목      2645 non-null   str
 3   내용      2645 non-null   str
 4   내용번호    2645 non-null   int64
dtypes: int64(2), str(3)
memory usage: 103.4 KB

In [7]:
df.dropna(inplace=True)

제목과 내용을 함께 사용해서 문서를 만들기 위해서 제목과 내용을 사이에 공백을 한 칸 넣어서 '+'로 연결해서 '문서'라는 파생 변수를 추가한다.

In [8]:
df['문서'] = df['제목'] + ' ' + df['내용']
df.head()

,번호,분류,제목,내용,내용번호,문서
0,2645,복지,아빠 육아휴직 장려금,아빠 육아휴직 장려금 업무개요 남성근로자의 육아휴직을 장려하고 양육에 따른 경...,23522464,아빠 육아휴직 장려금 아빠 육아휴직 장려금 업무개요 남성근로자의 육아휴직을 장...
1,2644,경제,[서울산업진흥원] 서울메이드란?,서울산업진흥원 서울메이드란 서울의 감성을 담은 다양하고 새로운 경험을 제공하기 위해...,23194045,[서울산업진흥원] 서울메이드란? 서울산업진흥원 서울메이드란 서울의 감성을 담은 다양...
2,2643,환경,(강북구) 정비중,강북구 정비중 업무개요 투명 폐트병을 교환보상하므로 수거율을 높이고 폐기물을 감...,23032485,(강북구) 정비중 강북구 정비중 업무개요 투명 폐트병을 교환보상하므로 수거율을 ...
3,2642,복지,"광진맘택시 운영(임산부,영아 양육가정 전용 택시)",광진맘택시 운영임산부영아 양육가정 전용 택시 업무개요 교통약자인 임산부와 영아가정...,22904492,"광진맘택시 운영(임산부,영아 양육가정 전용 택시) 광진맘택시 운영임산부영아 양육가정..."
4,2641,복지,마포 뇌병변장애인 비전센터,마포 뇌병변장애인 비전센터 마포뇌병변장애인 비전센터 운영 구분 내용 목적 학...,22477798,마포 뇌병변장애인 비전센터 마포 뇌병변장애인 비전센터 마포뇌병변장애인 비전센터 운영...

## BOW를 사용한 단어 벡터화

단어 토큰을 생성하고 각 단어의 개수를 세어 BOW 인코딩 벡터를 생성한다.

단어들의 출현 빈도(frequency)로 여러 문서를 벡터화하기 위해 CountVectorizer를 import 한다.

In [9]:
from sklearn.feature_extraction.text import CountVectorizer

In [10]:
cv = CountVectorizer(stop_words=['돋움', '경우', '또는'])
cv

CountVectorizer(stop_words=['돋움', '경우', '또는'])

fit_transform() 메소드로 문장에서 노출되는 feature(문서의 특징이 될 만한 단어) 문서 단어 희소 행렬(dtm_cv) 생성한다.

In [11]:
dtm_cv = cv.fit_transform(df['문서'])
dtm_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 118578 stored elements and shape (2645, 56651)>

In [12]:
dtm_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(2645, 56651))

In [13]:
vocab = cv.get_feature_names_out()
vocab

array(['03월', '08년', '10', ..., '힘쓴다', '힘을', '힘이'],
      shape=(56651,), dtype=object)

CountVectorizer 모델의 vocabulary_ 속성으로 어떤 단어들의 집합이 있는지 딕셔너리 형태로 확인할 수 있다.

In [14]:
cv.vocabulary_

{'아빠': 30166,
 '육아휴직': 35794,
 '장려금': 40098,
 '업무개요': 31494,
 '남성근로자의': 9780,
 '육아휴직을': 35798,
 '장려하고': 40101,
 '양육에': 31079,
 '따른': 14184,
 '경제적': 3650,
 '부담을': 20458,
 '완화함으로써': 33605,
 '일과': 37802,
 '가정생활의': 694,
 '양립': 31009,
 '가족친화적인': 784,
 '사회환경': 22911,
 '조성': 43603,
 '지원대상': 46358,
 '신청일': 29324,
 '기준': 8969,
 '이상': 36691,
 '계속하여': 3781,
 '서초구에': 24773,
 '주민등록': 44417,
 '되어': 13584,
 '있는': 38959,
 '육아휴직자': 35799,
 '대상자녀': 11880,
 '신청기간': 29232,
 '시작일': 28426,
 '이후': 37282,
 '개월부터': 1767,
 '종료일': 44002,
 '개월': 1753,
 '이내': 36439,
 '신청방법': 29260,
 '온라인': 33390,
 '서초구청': 24776,
 '홈페이지': 55328,
 '경로': 3421,
 '분야별정보': 21117,
 '복지': 20129,
 '영유아복지': 32834,
 '아빠육아휴직장려금': 30170,
 '신청': 29215,
 '바로가기': 17408,
 '방문': 18118,
 '동주민센터': 13431,
 '여성보육과': 31951,
 '구비서류': 6902,
 '고용센터': 4208,
 '발행': 18048,
 '육아휴직급여': 35795,
 '지급결정': 45803,
 '통지서': 51047,
 '주민등록등본': 44419,
 '부세대원': 20662,
 '이름과': 36609,
 '전입일자': 41564,
 '포함': 52225,
 '모든': 15657,
 '구성원': 6951,
 '주민번호': 44460,
 '뒷자리': 13756,
 '미포함': 17033,
 '지원내용': 46353,
 '매월': 15105,
 '만원지원기간': 14790,
 '최대': 49175,
 '서울산업진흥원': 24415,
 '서울메이드란': 24387,
 '서울의': 24617,
 '감성을': 1111,
 '담은': 11479,
 '다양하고': 11082,
 '새로운': 23745,
 '경험을': 3720,
 '제공하기': 42816,
 '위해': 35289,
 '만들어진': 14712,
 '라이프스타일': 14315,
 '플랫폼': 52610,
 '브랜드로': 21487,
 '서울이': 24624,
 '만들고': 14701,
 '세계가': 25680,
 '함께': 53854,
 '쓰는': 29938,
 '브랜드': 21486,
 '입니다': 38573,
 '기업과': 8841,
 '협업하여': 55078,
 '상품을': 23670,
 '발굴': 17776,
 '사용을': 22502,
 '원하는': 34818,
 '중소기업에게': 45368,
 '서울메이드': 24386,
 '제공': 42776,
 '관련홈페이지': 5774,
 '상세문의사항': 23453,
 '브랜드전략팀': 21492,
 '강북구': 1243,
 '정비중': 42447,
 '투명': 51212,
 '폐트병을': 52148,
 '교환보상하므로': 6654,
 '수거율을': 26704,
 '높이고': 10782,
 '폐기물을': 52073,
 '감량하여': 1033,
 '환경': 55760,
 '보호에': 19991,
 '기여': 8872,
 '업무설명': 31529,
 '페트병': 51857,
 '종량제봉투': 43964,
 '교환': 6652,
 '사업': 22131,
 '안내': 30318,
 '구분': 6832,
 '내용': 10035,
 '사업기간': 22167,
 '교환품목': 6665,
 '유색': 35478,
 '일회용': 38304,
 '요구르트': 33772,
 '식품': 28758,
 '포장용기': 52198,
 '식용유': 28727,
 '양념류': 30995,
 '제외': 42978,
 '대상': 11820,
 '관내': 5649,
 '구민': 6793,
 '누구나': 10819,
 '교환장소': 6663,
 '주민센터': 44476,
 '목요일': 15835,
 '한정': 53733,
 '처리방법': 48222,
 '개당': 1498,
 '이하': 37179,
 '유의사항': 35549,
 '물로': 16697,
 '헹구고': 54818,
 '비닐을': 21574,
 '제거한': 42754,
 '찌그러트려': 47467,
 '뚜껑을': 14254,
 '닫은': 11353,
 '제품만': 43305,
 '뚜껑만': 14252,
 '별도': 19188,
 '재활용하는': 40815,
 '단체에': 11324,
 '가져다주는': 729,
 '있음': 39155,
 '뚜껑': 14251,
 '닫아도': 11352,
 '가능': 304,
 '까지의': 9346,
 '실적을': 29612,
 '토대로': 50738,
 '동별': 13222,
 '우수자': 34214,
 '명에게': 15470,
 '재활용': 40800,
 '제품': 43302,
 '증정': 45708,
 '강북구민': 1245,
 '실적': 29605,
 '중복': 45333,
 '인정하지': 37645,
 '않음': 30662,
 '김아무개': 9285,
 '수유동': 27220,
 '등으로': 14069,
 '우수자여도': 34215,
 '제품은': 43312,
 '하나만': 52834,
 '광진맘택시': 6191,
 '운영': 34347,
 '임산부': 38427,
 '영아': 32721,
 '양육가정': 31072,
 '전용': 41503,
 '택시': 50606,
 '운영임산부영아': 34459,
 '교통약자인': 6596,
 '임산부와': 38431,
 '영아가정': 32722,
 '주민이': 44497,
 '병원': 19232,
 '진료를': 47092,
 '받으러': 17703,
 '쾌적하고': 50347,
 '안전하게': 30567,
 '이동할': 36519,
 '있도록': 39023,
 '대상자': 11878,
 '광진구에': 6184,
 '주민등록을': 44439,
 '자녀를': 39297,
 '가정': 676,
 '해당월의': 54133,
 '이전': 37073,
 '출생자부터': 49549,
 '이용가능': 36837,
 '회원가입': 56144,
 '가정당': 682,
 '만원': 14754,
 '택시이용권': 50653,
 '이용시기': 36904,
 '진료': 47080,
 '건강관리': 2191,
 '목적': 15858,
 '이동': 36481,
 '귀가': 7760,
 '사용': 22409,
 '의원': 36341,
 '한의원': 53720,
 '약국': 30950,
 '보건소': 19290,
 '산후조리원': 23122,
 '임산부아기': 38430,
 '건강프로그램임산부': 2238,
 '요가': 33750,
 '아기': 29985,
 '마사지': 14535,
 '진행시설': 47203,
 '이용방법': 36884,
 '신청서': 29272,
 '제출': 43225,
 '설치': 25285,
 '이용': 36836,
 '증빙자료': 45670,
 '확인서류': 55664,
 '이메일': 36623,
 '부터는': 20879,
 '앱택시으로': 30884,
 '다운로드': 11090,
 '광진구청': 6188,
 '분야별복지': 21115,
 '생애주기별복지': 23914,
 '보육여성': 19701,
 '여성임산부': 31975,
 '지원': 46326,
 '서비스': 24224,
 '운영사': 34409,
 '설치방법': 25335,
 '안드로이드': 30411,
 '플레이스토어': 52617,
 '아이폰': 30226,
 '에서': 31746,
 '아이엠택시': 30213,
 '검색': 2820,
 '호출': 55260,
 '본인': 20246,
 '계정': 3871,
 '쿠폰': 50353,
 '확인': 55628,
 '결제': 3203,
 '증빙자료병원영수증': 45674,
 '진료확인서': 47116,
 '제출방법': 43243,
 '신청회차': 29387,
 '부여일': 20728,
 '마포': 14636,
 '뇌병변장애인': 10813,
 '비전센터': 21723,
 '마포뇌병변장애인': 14649,
 '학령기': 53255,
 '곳이': 4399,
 '없는': 31635,
 '중증': 45504,
 '뇌병변': 10812,
 '장애인의': 40253,
 '교육돌봄건강': 6344,
 '맞춤종합서비스': 15000,
 '만세': 14735,
 '미만': 16883,
 '중증중복': 45513,
 '장애인': 40216,
 '이용시간': 36899,
 '평일': 52024,
 '수업시간': 27132,
 '이용료': 36879,
 '원식비': 34720,
 '기초생활수급자': 9055,
 '무료': 15998,
 '차상위계층': 47575,
 '감면식비': 1064,
 '개별': 1607,
 '특성': 51414,
 '욕구를': 33891,
 '기반으로': 8658,
 '교육': 6304,
 '돌봄': 13058,
 '건강': 2182,
 '등의': 14075,
 '종합서비스': 44128,
 '이용자': 36939,
 '모집': 15744,
 '기간에': 8445,
 '유선으로': 35491,
 '예약': 33048,
 '내방하여': 9965,
 '접수': 42013,
 '문의처': 16413,
 '마포뇌병변장애인비전센터': 14650,
 '마포구': 14637,
 '신촌로': 29404,
 '우리마포복지관': 34129,
 '기타사항': 9092,
 '상세': 23447,
 '문의는': 16386,
 '마포뇌병변장애인비전센터로': 14651,
 '문의': 16380,
 '2021년도': 54,
 '중1': 45200,
 '고1': 3954,
 '신입생': 29189,
 '입학준비금': 38828,
 '년도': 10189,
 '중고': 45239,
 '서울시는': 24475,
 '전국': 41144,
 '최초로': 49269,
 '년도부터': 10194,
 '자치구': 39746,
 '교육청과': 6465,
 '협력하여': 55057,
 '서울': 24300,
 '국공사립': 7344,
 '고고등기술': 4000,
 '특수각종학교에': 51425,
 '입학하는': 38833,
 '학생들을': 53282,
 '대상으로': 11858,
 '입학준비금을': 38829,
 '지원하여': 46476,
 '가정에': 699,
 '부담': 20436,
 '감소': 1113,
 '소득에': 26056,
 '관계없이': 5556,
 '교복': 6261,
 '의류': 36211,
 '스마트기기를': 27577,
 '교육의': 6419,
 '공공성': 4577,
 '강화': 1385,
 '보편적': 19906,
 '교육복지를': 6356,
 '실현하고자': 29694,
 '지급방식은': 45839,
 '학교에서': 53206,
 '학생학부모의': 53295,
 '신청을': 29315,
 '받아': 17679,
 '교복구매': 6262,
 '제로페이': 42887,
 '모바일': 15676,
 '포인트를': 52187,
 '지급하는': 45868,
 '방식이며': 18246,
 '구입범위는': 7038,
 '생활복': 23989,
 '체육복': 48811,
 '일상': 38054,
 '의류등교에': 36214,
 '필요한': 52762,
 '원격수업에': 34658,
 '스마트기기': 27576,
 '구매가능': 6770,
 '날짜': 9695,
 '지급방법': 45838,
 '진행되므로': 47184,
 '해당학교로': 54159,
 '문의해야함': 16437,
 '중고등학교': 45244,
 '범위': 18755,
 '구매범위': 6776,
 '태블릿': 50577,
 '노트북': 10447,
 '스마트': 27575,
 '기기': 8526,
 '비고': 21533,
 '구매': 6768,
 '학교별': 53191,
 '학칙에서': 53335,
 '정한': 42679,
 '형태에': 55187,
 '따라': 14169,
 '추진': 49338,
 '수업': 27125,
 '과제용': 5494,
 '등록된': 13927,
 '가맹점을': 490,
 '방문하여': 18178,
 '강화와': 1393,
 '실현하기': 29695,
 '위한': 35283,
 '사업으로': 22291,
 '신입생의': 29190,
 '준비에': 45123,
 '필수적인': 52712,
 '물품으로': 16769,
 '제한됨': 43340,
 '특수': 51423,
 '각종학교': 883,
 '전원': 41535,
 '지원금액': 46343,
 '인당': 37421,
 '만원학교로': 14793,
 '예산': 32976,
 '교부': 6268,
 '포인트': 52185,
 '지급': 45800,
 '사용방법': 22468,
 '학교주관구매': 53219,
 '교복비로': 6267,
 '처리': 48182,
 '주관구매': 44312,
 '등교의류와': 13832,
 '구매교복물려입기': 6771,
 '제로페이로': 42888,
 '사용코드': 22529,
 '방식의': 18244,
 '간편': 969,
 '활용': 56010,
 '중학생의': 45536,
 '학부모에게': 53272,
 '지급세': 45844,
 '불가': 21268,
 '서울시에': 24525,
 '신고': 28830,
 '수리된': 26910,
 '비인가': 21716,
 '대안교육기관에': 11928,
 '학교': 53175,
 '청소년의': 48657,
 '경우에도': 3577,
 '공교육': 4634,
 '학생들과': 53280,
 '같은': 1438,
 '방식인': 18247,
 '포인트로': 52186,
 '부모': 20550,
 '소득과': 26041,
 '원씩': 34722,
 '지급될': 45826,
 '예정이다': 33143,
 '위드유': 35009,
 '직장': 46992,
 '성희롱': 25672,
 '성폭력': 25655,
 '예방센터': 32935,
 '성희롱성폭력': 25673,
 '지원체계': 46459,
 '사각지대에': 21860,
 '시민이': 28149,
 '안전하고': 30568,
 '성평등하게': 25654,
 '일할': 38286,
 '민관': 17103,
 '협력을': 55053,
 '통해': 51117,
 '예방': 32921,
 '피해자': 52692,
 '체계': 48780,
 '예방센터위드유': 32936,
 '예방교육': 32925,
 '소규모': 26004,
 '사업장': 22338,
 '예방을': 32940,
 '맞춤형': 15004,
 '교육내용': 6334,
 '성희롱의': 25674,
 '개념과': 1486,
 '원인': 34748,
 '이해': 37210,
 '조직': 43728,
 '성평등': 25651,
 '문화': 16513,
 '점검': 41869,
 '고충사건의': 4307,
 '분쟁해결절차': 21239,
 '작성': 39838,
 '이메일접수': 36628,
 '조직문화': 43735,
 '컨설팅': 50235,
 '사업장에': 22342,
 '교육법률': 6354,
 '전문가를': 41291,
 '매칭하여': 15153,
 '진단': 47051,
 '솔루션': 26548,
 '컨설팅내용': 50236,
 '내부': 9969,
 '규정': 7833,
 '개선방안': 1659,
 '제시': 42929,
 '피해지원': 52696,
 '기반강화': 8646,
 '피해지원기관과': 52697,
 '연대하여': 32264,
 '피해지원의': 52698,
 '공백': 4908,
 '분야': 21107,
 '사업내용': 22170,
 '기관': 8479,
 '종사자': 44042,
 '역량': 32058,
 '법률동행': 18834,
 '대응': 11960,
 '강화를': 1389,
 '워크숍': 34640,
 '사례연구회': 21986,
 '정책': 42616,
 '협력사업': 55048,
 '네트워크': 10164,
 '협의회': 55103,
 '정보화': 42352,
 '확산': 55615,
 '확산을': 55623,
 '개선': 1650,
 '대시민': 11919,
 '홍보캠페인': 55395,
 '진행': 47172,
 '관련': 5683,
 '여성폭력': 31982,
 '상담여성긴급전화': 23331,
 '아동여성폭력피해자': 30086,
 '통합지원센터': 51111,
 '폭력피해': 52297,
 '이주여성': 37121,
 '원스톱': 34719,
 '지원센터': 46403,
 '성폭력성폭행': 25658,
 '가정폭력': 716,
 '성매매': 25517,
 '학교폭력': 53223,
 '주의사항특이사항': 44746,
 '센터위치': 25950,
 '중구': 45257,
 '무교로': 15965,
 '더익스체인지서울빌딩': 12300,
 '서울직장성희롱성폭력예방센터': 24658,
 '관련법규': 5712,
 '서울특별시': 24681,
 '여성폭력방지와': 31984,
 '피해자보호': 52693,
 '지원에': 46425,
 '관한': 6016,
 '조례': 43480,
 '성동구': 25493,
 '반려동물': 17553,
 '무료상담실': 16013,
 '무료상담실무엇이든': 16014,
 '물어보시개': 16717,
 '월월': 34925,
 '이용대상': 36870,
 '성동구민': 25495,
 '누구나취약계층': 10824,
 '우선': 34173,
 '배정': 18479,
 '상담일정': 23347,
 '첫째': 48488,
 '셋째': 25959,
 '금요일': 8216,
 '사전예약': 22688,
 '전화': 41729,
 '사전': 22670,
 '상담': 23287,
 '상담시간': 23320,
 '이내약자': 36451,
 '수에': 27141,
 '조정': 43694,
 '상담분야': 23305,
 '건강상태': 2212,
 '이상행동': 36750,
 '초기': 48932,
 '행동교정': 54368,
 '간단한': 897,
 '육아': 35783,
 '진찰': 47161,
 '촉진': 49018,
 '수의학적': 27233,
 '부분의': 20599,
 '문제해결': 16495,
 '방향': 18329,
 '대처방법': 12051,
 '정밀검사': 42277,
 '필요': 52715,
 '여부': 31886,
 '기존에': 8959,
 '잘못': 39977,
 '알고': 30672,
 '있던': 39020,
 '교정': 6499,
 '취약계층': 49755,
 '등록의무': 13976,
 '대상개월령': 11822,
 '개이': 1790,
 '미등록된': 16857,
 '동물등록': 13148,
 '장소': 40151,
 '구청': 7168,
 '전문상담실': 41326,
 '서울시': 24451,
 '우리동네꼼꼼육아정보': 34122,
 '책자': 48157,
 '책자서울시와': 48164,
 '서울시육아종합지원센터는': 24536,
 '명의': 15493,
 '우리동네': 34121,
 '보육반장이': 19675,
 '직접': 47012,
 '발로': 17873,
 '뛰어': 14267,
 '수집한': 27353,
 '지역': 46183,
 '육아정보를': 35788,
 '꼼꼼': 9377,
 '육아정보': 35787,
 '책자를': 48163,
 '자치구마다': 39760,
 '종씩': 44055,
 '발간하였으며': 17754,
 '책자에는': 48165,
 '보육반장': 19674,
 '소개': 25977,
 '육아종합지원센터': 35789,
 '생애주기별': 23913,
 '대상별': 11841,
 '등이': 14077,
 '담겨': 11391,
 '있다': 39005,
 '책자는': 48160,
 '출생신고를': 49546,
 '동주민센터에': 13436,
 '방문하는': 18163,
 '출산부모에게': 49537,
 '전달': 41204,
 '예정이며': 33144,
 '자치구의': 39773,
 '열린육아방': 32536,
 '공동육아나눔터': 4742,
 '부모와': 20568,
 '아이들이': 30198,
 '자주': 39707,
 '찾는': 48023,
 '곳에': 4391,
 '배포할': 18564,
 '인터넷': 37712,
 '보육포털서비스': 19723,
 '서울시육아정보': 24534,
 '꼼꼼육아정보': 9378,
 '서울특별시육아종합지원센터양육지원': 24707,
 '우리동네보육반장': 34123,
 '우리동네육아지원': 34125,
 '반반택시': 17565,
 '심야시간': 29766,
 '동승앱': 13288,
 '심야': 29765,
 '택시수요': 50622,
 '대비': 11803,
 '택시공급': 50609,
 '부족으로': 20796,
 '발생하는': 17910,
 '승차난': 27774,
 '해소를': 54204,
 '목적으로': 15869,
 '규제': 7863,
 '샌드박스': 23796,
 '실증특례': 29633,
 '지정된': 46596,
 '개시': 1726,
 '개시일': 1728,
 '반반택시앱': 17566,
 '안드로이드폰에서만': 30412,
 '아이폰은': 30227,
 '어플': 31356,
 '시스템': 28357,
 '개발중': 1576,
 '개발': 1528,
 '일정': 38193,
 '미정': 16982,
 '방식': 18237,
 '동승을': 13289,
 '승객이': 27713,
 '앱을': 30883,
 '자동으로': 39319,
 '동승객동성을': 13283,
 '매칭하고': 15152,
 '운전자를': 34557,
 '호출하는': 55264,
 '과거': 5396,
 '운전자가': 34555,
 '승객을': 27711,
 '선택해서': 25086,
 '합승하는것과': 53980,
 '다른': 10993,
 '동승객': 13282,
 '매칭방법': 15148,
 '인접지역': 37600,
 '동승구간이': 13285,
 '동승시': 13287,
 '추가예상': 49297,
 '시간이': 27870,
 '이하인': 37204,
 '경우에만': 3579,
 '동성': 13269,
 '매칭': 15147,
 '남남': 9716,
 '여여': 31992,
 '운행지역': 34607,
 '구제': 7099,
 '샌드박스에서': 23797,
 '승차난이': 27775,
 '많이': 14830,
 '강남구': 1181,
 '서초구': 24765,
 '종로구': 43968,
 '용산구': 33985,
 '영등포구': 32624,
 '구로구': 6730,
 '광진구': 6182,
 '동작구': 13405,
 '관악구': 5958,
 '시간': 27828,
 '시시': 28371,
 '요금산정': 33790,
 '미터기': 17015,
 '요금': 33786,
 '이용거리에': 36849,
 '비례하여': 21594,
 '반반씩': 17564,
 '지불': 46092,
 '호출료': 55261,
 '천원은': 48375,
 '건당': 2267,
 '천원': 48372,
 '이용절차': 36953,
 '사전에': 22685,
 '승객기사': 27705,
 '신용체크카드': 29143,
 '등록': 13910,
 '인의': 37550,
 '앱에서': 30881,
 '동승': 13281,
 '요청': 33862,
 '이동경로가': 36484,
 '유사한': 35471,
 '동승구간': 13284,
 '추가': 49278,
 '예상시간': 33015,
 '경우에': 3574,
 '한정하여': 53741,
 '실시간': 29539,
 '택시기사에': 50612,
 '승객들은인인': 27706,
 '배정된': 18482,
 '좌석앞': 44182,
 '탑승': 50542,
 '최종': 49247,
 '목적지': 15880,
 '도착': 12943,
 '택시기사가': 50611,
 '하차': 53133,
 '승객의': 27712,
 '금액을': 8206,
 '입력하고': 38593,
 '승객간': 27704,
 '이동거리비율을': 36483,
 '계산하여': 3769,
 '요금플랫폼': 33801,
 '자동산정': 39315,
 '코나투스': 50275,
 '고객센터': 3983,
 '택시물류과': 50618,
 '이호상': 37267,
 '사회서비스원은': 22871,
 '무엇을': 16117,
 '하는': 52910,
 '곳인가요': 4403,
 '사회서비스': 22868,
 '분야에서': 21120,
 '공공부문의': 4564,
 '역할을': 32126,
 '강화하기': 1396,
 '서울시가': 24452,
 '설립한': 25210,
 '출연기관입니다': 49571,
 '국공립': 7336,
 '사회복지시설을': 22864,
 '운영하고': 34493,
 '종합재가센터를': 44141,
 '설치해서': 25408,
 '운영하며': 34502,
 '민간': 17052,
 '서비스기관에': 24229,
 '재무회계노무': 40513,
 '컨설팅을': 50239,
 '지원합니다': 46485,
 '자세한': 39501,
 '사항은': 22789,
 '사회서비스원': 22870,
 '홈페이지를': 55335,
 '참고하여': 47759,
 '주십시오': 44649,
 '주요문의사항': 44678,
 '더보기': 12294,
 '대표번호': 12127,
 '종료사업': 43996,
 'taxi': 189,
 '에스택시': 31752,
 '서울택시승차앱': 24676,
 '시범운영': 28186,
 '시범운영업무개요': 28188,
 '빈차를': 21789,
 '보고': 19323,
 '택시를': 50617,
 '기본적인': 8711,
 '기능을': 8571,
 '오프라인에서': 33312,
 '온라인까지': 33393,
 '확대하는': 55579,
 '개념을': 1490,
 '적용한': 41061,
 '선택운영기간': 25074,
 '종료앱': 44001,
 '구글': 6699,
 '다운받아': 11098,
 '서울택시': 24675,
 '공공승차': 4580,
 '시민승차': 28133,
 '등으로도': 14070,
 '검색가능': 2821,
 '기간': 8428,
 '기반의': 8660,
 '스마트폰만': 27581,
 '기타구분민간호출앱서울택시승차앱운영방식택시운수종사자의': 9079,
 '스마트폰택시결제기승차방식목적지를': 27586,
 '표출하여': 52426,
 '운전기사가': 34541,
 '고름시민이': 4084,
 '부르는': 20545,
 '택시운수종사자는': 50630,
 '별도의': 19197,
 '설치작업없이': 25370,
 '택시결제기를': 50608,
 '이용동의만': 36874,
 '거치면': 2166,
 '서울택시승차앱은': 24677,
 '전체': 41641,
 '적용': 40996,
 '보도자료': 19439,
 '장기요양': 40062,
 '이동지원서비스': 36502,
 '모두타': 15655,
 '돌봄택시': 13065,
 '이동지원서비스모두타': 36503,
 '보건복지부와': 19285,
 '서울시택시운송사업조합의': 24571,
 '민관협력사업으로': 17107,
 '거동이': 2028,
 '불편한': 21454,
 '어르신도': 31236,
 '방문을': 18145,
 '비롯한': 21598,
 '외출권을': 33735,
 '보장할': 19772,
 '시범사업': 28179,
 '시행': 28568,
 '코로나': 50284,
 '지속과': 46140,
 '운영자': 34460,
 '지속': 46134,
 '사유로': 22596,
 '일부로': 38033,
 '종료': 43986,
 '예정': 33122,
 '업무내용': 31507,
 '실제': 29622,
 '거주하는': 2137,
 '등급': 13837,
 '수급자': 26720,
 '시설급여를': 28257,
 '이용하지': 36988,
 '않은': 30657,
 '재가급여수급자': 40373,
 '휠체어': 56427,
 '유무와': 35451,
 '월토': 34963,
 '공휴일': 5386,
 '이용요금': 36924,
 '한도액': 53616,
 '시범사업기간': 28181,
 '동안': 13308,
 '본인부담금': 20251,
 '없음': 31689,
 '내에서': 10010,
 '자유롭게': 39638,
 '중형택시': 45540,
 '요금에': 33791,
 '서비스요금원': 24244,
 '기본요금': 8701,
 '거리당': 2053,
 '이용지역': 36961,
 '서울시내에서만': 24468,
 '가능시외운행': 316,
 '이용신청공단': 36907,
 '전용카드': 41531,
 '발급': 17788,
 '콜센터를': 50342,
 '통한': 51076,
 '배차예약': 18507,
 '차량이용': 47542,
 '확인을': 55678,
 '지참': 46678,
 '소재': 26367,
 '가까운': 291,
 '국민건강보험공단': 7400,
 '노인장기요양보험': 10419,
 '운영센터': 34421,
 '방문신청만': 18140,
 '원칙': 34795,
 '신체상태': 29394,
 '인지기능저하로': 37686,
 '본인이': 20265,
 '가족친족': 782,
 '대리': 11735,
 '가족친족이': 783,
 '없고': 31623,
 '독거인': 12970,
 '이해관계인': 37213,
 '신청불가': 29266,
 '공단지사': 4702,
 '영등포북부': 32636,
 '서초북부': 24782,
 '강남동부': 1186,
 '강남북부': 1188,
 '이동지원': 36501,
 '이용신청서': 36909,
 '개인정보': 1845,
 '수집이용': 27348,
 '제자': 43032,
 '동의서': 13338,
 '신분증': 29075,
 '추가서류': 49295,
 '가족관계를': 743,
 '확인할': 55705,
 '가족관계증명서': 747,
 '가족': 735,
 '친족': 50014,
 '외에': 33724,
 '신청하는': 29361,
 '이해관계인의': 37215,
 '위임장': 35168,
 '전용카드의': 41532,
 '월한도액은': 34968,
 '월말에': 34886,
 '소멸되어': 26088,
 '이월': 37007,
 '월중': 34952,
 '카드를': 50111,
 '발급받은': 17821,
 '시점부터': 28486,
 '말일까지': 14886,
 '잔액보다': 39954,
 '이용금액이': 36863,
 '많은': 14825,
 '초과되는': 48910,
 '전액': 41476,
 '문의에': 16405,
 '담당처': 11440,
 '상이': 23582,
 '예약센터': 33060,
 '예약관련': 33049,
 '제도': 42850,
 '국민건간보험공단': 7398,
 '부당요금': 20474,
 '승차거부': 27769,
 '여객자동차': 31805,
 '운수사업법과': 34332,
 '관련한': 5768,
 '택시불편신고는': 50620,
 '일반': 37854,
 '택시와': 50623,
 '동일하게': 13394,
 '취약가구': 49754,
 '중성화': 45359,
 '동물등록중성화': 13152,
 '지원구분': 46333,
 '동물돌봄의료서비스는': 13145,
 '반려동물의': 17557,
 ...}

벡터를 표현하려면 단어 가방에 있는 모든 단어를 행렬값으로 나타내야 한다. toarray() 메소드로 희소 행렬을 넘파이 배열로 변환하고 get_feature_names_out() 메소드를 실행해서 불러온 단어 목록을 데이터프레임으로 만들어서 확인한다.

In [15]:
pd.DataFrame(dtm_cv.toarray(), columns=vocab)

,03월,08년,10,100명이상인,100세가,10만원,10만원상당,10명이고,10인승,10인의,...,힐링프로그램을,힐링하는,힐스테이트,힘들,힘들경우,힘들고,힘쓰고있습니다,힘쓴다,힘을,힘이
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2640,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2641,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2642,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2643,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2644,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

희소 행렬을 단어 목록별로 출현 횟수를 sum() 메소드로 계산해서 출현 횟수의 오름차순으로 정렬한다.  
오름차순으로 정렬한 결과를 보면 아랫부분에 '돋움', '있는', '있습니다' 같은 고빈도 단어들이 있다. 이러한 단어들은 불용어로 다룰 것인지 고려해야 한다.

In [16]:
pd.DataFrame(dtm_cv.toarray(), columns=vocab).sum().sort_values()

힐스테이트        1
힐링하는         1
힐링프로그램을      1
18세          1
19           1
          ...
대한         394
서울시        578
어떻게        597
있습니다       685
있는         718
Length: 56651, dtype: int64

## 잠재 디리클레 할당 적용하기

정답인 '분류'의 유일한 값을 확인해서 토픽의 개수를 확인하자.

In [17]:
print(df.분류.value_counts())
NUM_TOPICS = len(set(df['분류']))
print(NUM_TOPICS)

분류
행정        1098
경제         823
복지         217
환경         124
주택도시계획     110
문화관광        96
교통          90
안전          51
건강          23
여성가족        13
Name: count, dtype: int64
10

각 문서에 어떤 주제들이 있는지 확인하는 사이킷런의 잠재 디리클레 분석을 사용하기 위해서 LatentDirichletAllocation를 import 한다.

In [18]:
from sklearn.decomposition import LatentDirichletAllocation

n_components 하이퍼파라미터에 분석할 토픽의 개수(기본값 10)를 설정하고 모델을 만든다. 재현성(매번 똑같은 결과)을 위해 random_state를 설정했다.

In [19]:
LDA_model = LatentDirichletAllocation(n_components=NUM_TOPICS, random_state=42)
LDA_model

LatentDirichletAllocation(random_state=42)

fit() 메소드로 작성된 LDA 모델에 문서 단어 행렬(dtm_cv)을 넣어 학습시킨다.

In [20]:
LDA_model.fit(dtm_cv)

LatentDirichletAllocation(random_state=42)

# pyLDAvis를 통한 LDA 토픽 모델 시각화

pyLDAvis는 파이썬의 토픽 모델링을 구현해 주는 좋은 도구로 사용자 말뭉치의 토픽을 자동으로 추출해 해석하고 대화형 웹 기반으로 시각화할 수 있도록 설계되었다. 시각화 결과는 IPython 노트북에서 사용하기 위한 것이지만, 독립 실행형 HTML 파일로 저장해서 쉽게 공유할 수 있다.

어떤 방법으로 전처리와 모데링을 해 주느냐에 따라 pyLDAvis로 토픽 모델링한 결과 또한 다르게 나타난다. 다음은 BOW 방식으로 벡터화했을 때의 결과이다. 모델링에서 최적화한 토픽별 대표 단어들을 반환한 뒤 t-SNE(t-Distributed Stochastic Neighbor Embedding)을 통해 고차원 데이터를 2차원으로 차원 축소해 시각화 한다. t-SNE는 고차원 데이터를 2D나 3D 공간으로 줄여 눈으로 직접 확인할 수 있게 만드는 대표적인 시각화용 차원 축소 알고리즘이다.

LDA 토픽 모델을 시각화하기 위해서 pyLDAvis를 설치하고 import 한다.  
pyLDAvis 버전 `3.4.0`부터 라이브러리 내부 구조가 `변경`돼서 기존에 사용하던 pyLDAvis.sklearn 대신에 `pyLDAvis.lda_model`를 사용해야 한다.

In [21]:
import pyLDAvis.lda_model

prepare() 메소드로 LDA 토픽 모델링을 시각화 한다.  
`lda_model`: 학습이 완료된 LDA 토픽 모델링 객체를 지정한다.  
`dtm`: CountVectorizer나 TfidfVectorizer를 통해 변환된 문서 단어 행렬 객체를 지정한다.  
`vectorizer`: 2번째 인수인 `dtm` 생성할 때 사용한 벡터라이저 객체를 지정한다.  
`mds`: 시각화에 사용할 다차원 축소 알고리즘(Multi-Dimensional Scaling)을 지정한다. `pcoa`가 기본값이고 Principal Component Analysis를 의미한다.

## LDA 토픽 모델링 시각화 결과를 IPython으로 출력하기

`pyLDAvis.enable_notebook()`  
`pyLDAvis.lda_model.prepare(lda_model=LDA_model, dtm=dtm_cv, vectorizer=cv, mds='tsne')`

## LDA 토픽 모델링 시각화 결과를 HTML 파일로 출력하기

save_html() 메소드를 사용하면 LDA 토픽 모델링 시각화 결과를 HTML 파일로 만든다.  
`data`: prepare() 메소드로 LDA 토픽 모델링 시각화 명령을 지정한다.  
`fileobj`: HTML 파일의 경로와 이름을 지정한다.

In [22]:
pyLDAvis.save_html(data=pyLDAvis.lda_model.prepare(lda_model=LDA_model, dtm=dtm_cv, vectorizer=cv, mds='tsne'), fileobj='./lda_result.html')

pyLDAvis로 시각화한 LDA 토픽 모델링 결과는 왼쪽의 지도와 오른쪽의 막대그래프로 구성된다.

<img src="./LDA토픽모델링시각화.png" width="1200" align="left" />

## 왼쪽 화면

토픽 간 거리 지도(Intertopic Distance Map), 전체 데이터셋에서 추출된 토픽들이 서로 어떤 관계를 맺고 있는지 보여준다.  
원의 크기: 해당 토픽이 전체 문서에서 차지하는 비중 원이 클수록 많은 문서에 다뤄진 주요 주제이다.  
원의 위치: 토픽 간의 유사성을 나타낸다.  
&nbsp;&nbsp;&nbsp;▶ 멀리 떨어져 있을수록 주제가 뚜렷하게 구분되는 독립적인 토픽이다. 이상적인 결과.  
&nbsp;&nbsp;&nbsp;▶ 많이 겹쳐 있을수록 두 토픽이 공유하는 단어가 많아 주제가 중복될 가능성이 크다. 토픽 개수를 줄여서 다시 모델링하는 것이 좋다.

## 오른쪽 화면

주요 단어 목록(Top-30 Most Salient Terms)으로 토픽 간 거리 지도에서 특정 원(토픽)을 클릭했을 때 나타는 단어들의 분포이다.  
▶ 하늘색 막대(Overall term frequency)는 해당 단어가 전체 데이터에서 나타는 총 빈도이다.  
▶ 빨간색 막대(Estimated term frequency within the selected topic)는 해당 단어가 선택한 토픽 내에서 나타나는 빈도이다.  
해석하는 방법은 하늘색 대비 빨간색 비중이 높을수록, 그 단어는 해당 토픽을 정의하는 핵심 키워드라고 볼 수 있다.

## 오른쪽 상단의 슬라이더

람다($\lambda$)값 조절  
$\lambda$값을 조절하면 단어 리스트의 정렬 기준이 바뀐다. 토픽의 이름을 정의할 때 매우 중요하다.  
$\lambda$를 1로 설정하면 토픽 내 빈도수가 높은 순서로 보여준다.  
$\lambda$를 0으로 설정하면 다른 토픽에는 거의 없고 해당 토픽에서만 독보적으로 등장하는 단어 위주로 보여준다. 토픽의 정체성 파악하기 좋다.  
$\lambda$의 추천 설정은 0.6으로 일반적으로 가장 해석이 쉬운 중첩 지점이다. 이 설정에서 상위 5 ~ 10개 단어를 보고 토픽 이름을 결정한다.

In [23]:
vis_data = pyLDAvis.lda_model.prepare(LDA_model, dtm_cv, cv, mds='tsne')
topic_df = vis_data.topic_info
topic_df.head()

        Term   Freq  Total Category  logprob  loglift
119      amp   63.0   63.0  Default     30.0     30.0
39480   자본금은   52.0   52.0  Default     29.0     29.0
36388     의한  205.0  205.0  Default     28.0     28.0
8795   기술능력과   34.0   34.0  Default     27.0     27.0
31204    어떻게  441.0  441.0  Default     26.0     26.0

pyLDAvis에서 생성되는 topic_df(vis_data.topic_info) 데이터프레임의 Category 열은 시각화 화면의 우측 바 차트에 출력할 단어들의 필터링 상태를 나타낸다.  
Category 열에는 데이터프레임 전체 행에 걸쳐 크게 두 가지 형태의 문자열 값이 저장된다.  
'Default'는 특정 토픽을 선택하지 않은 전체 데이터셋 상태를 나타낸다.  
'Topic1', 'Topic2', 'Topic3', ... 는 각 개별 토픽 상태를 나타낸다.

In [24]:
for i in range(1, LDA_model.n_components + 1):
    topic_keywords = topic_df[topic_df.Category == f'Topic{i}'].head(10)['Term'].values
    print(f'Topic{i}: {", ".join(topic_keywords)}')

Topic1: 자본금은, 기술능력과, 건설기술자, 바닥면적의, 관련종목의, 제종근린생활시설, 기술자격취득자, 대기환경보전법에, 되나요건설기술관리법에, 용도에
Topic2: 장기기증, 현금영수증, 여론조사, 트레킹, 시가지, 여성이룸센터, 지그재그, 제강, 청원, 환자안심병원
Topic3: amp, apos, 체험요금, 임신출산, 정읍, 수련관, 맘편한카드, 차상위, 신상정보, 무안
Topic4: 급식, 용인, 교복, 예체능, 챌린지, 서북병원, 세대주가, 청약부금, 청약예금, 금주
Topic5: 원어민, 영어회화, 특별활동, 승합, 화물, 잠수교, 신체활동리더, 승용, 상시근로자수, 홍제천
Topic6: 층평일, 주민대상, 서울함, 권리가액이, 외국인주민, 한강의, 이색달리기, 분양받을, 증강현실, 분양건축물의
Topic7: 치매지원센터, 의료기관이, 구의아리수정수센터, 서울상, 서울특별시육아종합지원센터, 후계농업경영인, 봉수대, 자격정지, 보육서비스, 콘테스트
Topic8: 나와서, 버스이용, 계약심사, 천세대, 일은, 전달합니다, 상대방의, 중계사가, 통화내용을, 주택단지의
Topic9: 기획예산과, 전산정보과, 빈집, 개인회생, 제조구매, 주택용, 처리한, 친구의, 광화문시민열린마당, 남산동
Topic10: 시간외, 서커스, 이행기준, 심사요청, 재배정사업, 관리규약에, 구성원의, 점자스티커, 길음동, 스트리트

## TF-IDF를 사용한 단어 벡터화

단어들의 출현 빈도를 TF-IDF 방식으로 단어의 가중치를 조정한 여러 문서를 벡터화하기 위해 TfidfVectorizer를 import 한다.

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [26]:
tfidf = TfidfVectorizer(stop_words=['돋움', '경우', '또는', '있습니다', '있는', '합니다'])
tfidf

TfidfVectorizer(stop_words=['돋움', '경우', '또는', '있습니다', '있는', '합니다'])

fit_transform() 메소드로 문장에서 노출되는 feature(문서의 특징이 될 만한 단어) 문서 단어 희소 행렬(dtm_tfidf) 생성한다.

In [27]:
dtm_tfidf = tfidf.fit_transform(df['문서'])
dtm_tfidf

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 117379 stored elements and shape (2645, 56648)>

In [28]:
dtm_tfidf.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(2645, 56648))

In [29]:
vocab = tfidf.get_feature_names_out()
vocab

array(['03월', '08년', '10', ..., '힘쓴다', '힘을', '힘이'],
      shape=(56648,), dtype=object)

In [30]:
tfidf.vocabulary_

{'아빠': 30166,
 '육아휴직': 35794,
 '장려금': 40096,
 '업무개요': 31494,
 '남성근로자의': 9780,
 '육아휴직을': 35798,
 '장려하고': 40099,
 '양육에': 31079,
 '따른': 14184,
 '경제적': 3650,
 '부담을': 20458,
 '완화함으로써': 33605,
 '일과': 37802,
 '가정생활의': 694,
 '양립': 31009,
 '가족친화적인': 784,
 '사회환경': 22911,
 '조성': 43601,
 '지원대상': 46356,
 '신청일': 29324,
 '기준': 8969,
 '이상': 36691,
 '계속하여': 3781,
 '서초구에': 24773,
 '주민등록': 44415,
 '되어': 13584,
 '육아휴직자': 35799,
 '대상자녀': 11880,
 '신청기간': 29232,
 '시작일': 28426,
 '이후': 37282,
 '개월부터': 1767,
 '종료일': 44000,
 '개월': 1753,
 '이내': 36439,
 '신청방법': 29260,
 '온라인': 33390,
 '서초구청': 24776,
 '홈페이지': 55325,
 '경로': 3421,
 '분야별정보': 21117,
 '복지': 20129,
 '영유아복지': 32834,
 '아빠육아휴직장려금': 30170,
 '신청': 29215,
 '바로가기': 17408,
 '방문': 18118,
 '동주민센터': 13431,
 '여성보육과': 31951,
 '구비서류': 6902,
 '고용센터': 4208,
 '발행': 18048,
 '육아휴직급여': 35795,
 '지급결정': 45801,
 '통지서': 51045,
 '주민등록등본': 44417,
 '부세대원': 20662,
 '이름과': 36609,
 '전입일자': 41562,
 '포함': 52223,
 '모든': 15657,
 '구성원': 6951,
 '주민번호': 44458,
 '뒷자리': 13756,
 '미포함': 17033,
 '지원내용': 46351,
 '매월': 15105,
 '만원지원기간': 14790,
 '최대': 49173,
 '서울산업진흥원': 24415,
 '서울메이드란': 24387,
 '서울의': 24617,
 '감성을': 1111,
 '담은': 11479,
 '다양하고': 11082,
 '새로운': 23745,
 '경험을': 3720,
 '제공하기': 42814,
 '위해': 35289,
 '만들어진': 14712,
 '라이프스타일': 14315,
 '플랫폼': 52608,
 '브랜드로': 21487,
 '서울이': 24624,
 '만들고': 14701,
 '세계가': 25680,
 '함께': 53852,
 '쓰는': 29938,
 '브랜드': 21486,
 '입니다': 38573,
 '기업과': 8841,
 '협업하여': 55075,
 '상품을': 23670,
 '발굴': 17776,
 '사용을': 22502,
 '원하는': 34818,
 '중소기업에게': 45366,
 '서울메이드': 24386,
 '제공': 42774,
 '관련홈페이지': 5774,
 '상세문의사항': 23453,
 '브랜드전략팀': 21492,
 '강북구': 1243,
 '정비중': 42445,
 '투명': 51210,
 '폐트병을': 52146,
 '교환보상하므로': 6654,
 '수거율을': 26704,
 '높이고': 10782,
 '폐기물을': 52071,
 '감량하여': 1033,
 '환경': 55757,
 '보호에': 19991,
 '기여': 8872,
 '업무설명': 31529,
 '페트병': 51855,
 '종량제봉투': 43962,
 '교환': 6652,
 '사업': 22131,
 '안내': 30318,
 '구분': 6832,
 '내용': 10035,
 '사업기간': 22167,
 '교환품목': 6665,
 '유색': 35478,
 '일회용': 38304,
 '요구르트': 33772,
 '식품': 28758,
 '포장용기': 52196,
 '식용유': 28727,
 '양념류': 30995,
 '제외': 42976,
 '대상': 11820,
 '관내': 5649,
 '구민': 6793,
 '누구나': 10819,
 '교환장소': 6663,
 '주민센터': 44474,
 '목요일': 15835,
 '한정': 53731,
 '처리방법': 48220,
 '개당': 1498,
 '이하': 37179,
 '유의사항': 35549,
 '물로': 16697,
 '헹구고': 54815,
 '비닐을': 21574,
 '제거한': 42752,
 '찌그러트려': 47465,
 '뚜껑을': 14254,
 '닫은': 11353,
 '제품만': 43303,
 '뚜껑만': 14252,
 '별도': 19188,
 '재활용하는': 40813,
 '단체에': 11324,
 '가져다주는': 729,
 '있음': 39153,
 '뚜껑': 14251,
 '닫아도': 11352,
 '가능': 304,
 '까지의': 9346,
 '실적을': 29612,
 '토대로': 50736,
 '동별': 13222,
 '우수자': 34214,
 '명에게': 15470,
 '재활용': 40798,
 '제품': 43300,
 '증정': 45706,
 '강북구민': 1245,
 '실적': 29605,
 '중복': 45331,
 '인정하지': 37645,
 '않음': 30662,
 '김아무개': 9285,
 '수유동': 27220,
 '등으로': 14069,
 '우수자여도': 34215,
 '제품은': 43310,
 '하나만': 52832,
 '광진맘택시': 6191,
 '운영': 34347,
 '임산부': 38427,
 '영아': 32721,
 '양육가정': 31072,
 '전용': 41501,
 '택시': 50604,
 '운영임산부영아': 34459,
 '교통약자인': 6596,
 '임산부와': 38431,
 '영아가정': 32722,
 '주민이': 44495,
 '병원': 19232,
 '진료를': 47090,
 '받으러': 17703,
 '쾌적하고': 50345,
 '안전하게': 30567,
 '이동할': 36519,
 '있도록': 39022,
 '대상자': 11878,
 '광진구에': 6184,
 '주민등록을': 44437,
 '자녀를': 39295,
 '가정': 676,
 '해당월의': 54130,
 '이전': 37073,
 '출생자부터': 49547,
 '이용가능': 36837,
 '회원가입': 56141,
 '가정당': 682,
 '만원': 14754,
 '택시이용권': 50651,
 '이용시기': 36904,
 '진료': 47078,
 '건강관리': 2191,
 '목적': 15858,
 '이동': 36481,
 '귀가': 7760,
 '사용': 22409,
 '의원': 36341,
 '한의원': 53718,
 '약국': 30950,
 '보건소': 19290,
 '산후조리원': 23122,
 '임산부아기': 38430,
 '건강프로그램임산부': 2238,
 '요가': 33750,
 '아기': 29985,
 '마사지': 14535,
 '진행시설': 47201,
 '이용방법': 36884,
 '신청서': 29272,
 '제출': 43223,
 '설치': 25285,
 '이용': 36836,
 '증빙자료': 45668,
 '확인서류': 55661,
 '이메일': 36623,
 '부터는': 20879,
 '앱택시으로': 30884,
 '다운로드': 11090,
 '광진구청': 6188,
 '분야별복지': 21115,
 '생애주기별복지': 23914,
 '보육여성': 19701,
 '여성임산부': 31975,
 '지원': 46324,
 '서비스': 24224,
 '운영사': 34409,
 '설치방법': 25335,
 '안드로이드': 30411,
 '플레이스토어': 52615,
 '아이폰': 30226,
 '에서': 31746,
 '아이엠택시': 30213,
 '검색': 2820,
 '호출': 55257,
 '본인': 20246,
 '계정': 3871,
 '쿠폰': 50351,
 '확인': 55625,
 '결제': 3203,
 '증빙자료병원영수증': 45672,
 '진료확인서': 47114,
 '제출방법': 43241,
 '신청회차': 29387,
 '부여일': 20728,
 '마포': 14636,
 '뇌병변장애인': 10813,
 '비전센터': 21723,
 '마포뇌병변장애인': 14649,
 '학령기': 53253,
 '곳이': 4399,
 '없는': 31635,
 '중증': 45502,
 '뇌병변': 10812,
 '장애인의': 40251,
 '교육돌봄건강': 6344,
 '맞춤종합서비스': 15000,
 '만세': 14735,
 '미만': 16883,
 '중증중복': 45511,
 '장애인': 40214,
 '이용시간': 36899,
 '평일': 52022,
 '수업시간': 27132,
 '이용료': 36879,
 '원식비': 34720,
 '기초생활수급자': 9055,
 '무료': 15998,
 '차상위계층': 47573,
 '감면식비': 1064,
 '개별': 1607,
 '특성': 51412,
 '욕구를': 33891,
 '기반으로': 8658,
 '교육': 6304,
 '돌봄': 13058,
 '건강': 2182,
 '등의': 14075,
 '종합서비스': 44126,
 '이용자': 36939,
 '모집': 15744,
 '기간에': 8445,
 '유선으로': 35491,
 '예약': 33048,
 '내방하여': 9965,
 '접수': 42011,
 '문의처': 16413,
 '마포뇌병변장애인비전센터': 14650,
 '마포구': 14637,
 '신촌로': 29404,
 '우리마포복지관': 34129,
 '기타사항': 9092,
 '상세': 23447,
 '문의는': 16386,
 '마포뇌병변장애인비전센터로': 14651,
 '문의': 16380,
 '2021년도': 54,
 '중1': 45198,
 '고1': 3954,
 '신입생': 29189,
 '입학준비금': 38828,
 '년도': 10189,
 '중고': 45237,
 '서울시는': 24475,
 '전국': 41142,
 '최초로': 49267,
 '년도부터': 10194,
 '자치구': 39744,
 '교육청과': 6465,
 '협력하여': 55054,
 '서울': 24300,
 '국공사립': 7344,
 '고고등기술': 4000,
 '특수각종학교에': 51423,
 '입학하는': 38833,
 '학생들을': 53280,
 '대상으로': 11858,
 '입학준비금을': 38829,
 '지원하여': 46474,
 '가정에': 699,
 '부담': 20436,
 '감소': 1113,
 '소득에': 26056,
 '관계없이': 5556,
 '교복': 6261,
 '의류': 36211,
 '스마트기기를': 27577,
 '교육의': 6419,
 '공공성': 4577,
 '강화': 1385,
 '보편적': 19906,
 '교육복지를': 6356,
 '실현하고자': 29694,
 '지급방식은': 45837,
 '학교에서': 53204,
 '학생학부모의': 53293,
 '신청을': 29315,
 '받아': 17679,
 '교복구매': 6262,
 '제로페이': 42885,
 '모바일': 15676,
 '포인트를': 52185,
 '지급하는': 45866,
 '방식이며': 18246,
 '구입범위는': 7038,
 '생활복': 23989,
 '체육복': 48809,
 '일상': 38054,
 '의류등교에': 36214,
 '필요한': 52760,
 '원격수업에': 34658,
 '스마트기기': 27576,
 '구매가능': 6770,
 '날짜': 9695,
 '지급방법': 45836,
 '진행되므로': 47182,
 '해당학교로': 54156,
 '문의해야함': 16437,
 '중고등학교': 45242,
 '범위': 18755,
 '구매범위': 6776,
 '태블릿': 50575,
 '노트북': 10447,
 '스마트': 27575,
 '기기': 8526,
 '비고': 21533,
 '구매': 6768,
 '학교별': 53189,
 '학칙에서': 53333,
 '정한': 42677,
 '형태에': 55184,
 '따라': 14169,
 '추진': 49336,
 '수업': 27125,
 '과제용': 5494,
 '등록된': 13927,
 '가맹점을': 490,
 '방문하여': 18178,
 '강화와': 1393,
 '실현하기': 29695,
 '위한': 35283,
 '사업으로': 22291,
 '신입생의': 29190,
 '준비에': 45121,
 '필수적인': 52710,
 '물품으로': 16769,
 '제한됨': 43338,
 '특수': 51421,
 '각종학교': 883,
 '전원': 41533,
 '지원금액': 46341,
 '인당': 37421,
 '만원학교로': 14793,
 '예산': 32976,
 '교부': 6268,
 '포인트': 52183,
 '지급': 45798,
 '사용방법': 22468,
 '학교주관구매': 53217,
 '교복비로': 6267,
 '처리': 48180,
 '주관구매': 44310,
 '등교의류와': 13832,
 '구매교복물려입기': 6771,
 '제로페이로': 42886,
 '사용코드': 22529,
 '방식의': 18244,
 '간편': 969,
 '활용': 56007,
 '중학생의': 45534,
 '학부모에게': 53270,
 '지급세': 45842,
 '불가': 21268,
 '서울시에': 24525,
 '신고': 28830,
 '수리된': 26910,
 '비인가': 21716,
 '대안교육기관에': 11928,
 '학교': 53173,
 '청소년의': 48655,
 '경우에도': 3577,
 '공교육': 4634,
 '학생들과': 53278,
 '같은': 1438,
 '방식인': 18247,
 '포인트로': 52184,
 '부모': 20550,
 '소득과': 26041,
 '원씩': 34722,
 '지급될': 45824,
 '예정이다': 33143,
 '위드유': 35009,
 '직장': 46990,
 '성희롱': 25672,
 '성폭력': 25655,
 '예방센터': 32935,
 '성희롱성폭력': 25673,
 '지원체계': 46457,
 '사각지대에': 21860,
 '시민이': 28149,
 '안전하고': 30568,
 '성평등하게': 25654,
 '일할': 38286,
 '민관': 17103,
 '협력을': 55050,
 '통해': 51115,
 '예방': 32921,
 '피해자': 52690,
 '체계': 48778,
 '예방센터위드유': 32936,
 '예방교육': 32925,
 '소규모': 26004,
 '사업장': 22338,
 '예방을': 32940,
 '맞춤형': 15004,
 '교육내용': 6334,
 '성희롱의': 25674,
 '개념과': 1486,
 '원인': 34748,
 '이해': 37210,
 '조직': 43726,
 '성평등': 25651,
 '문화': 16513,
 '점검': 41867,
 '고충사건의': 4307,
 '분쟁해결절차': 21239,
 '작성': 39836,
 '이메일접수': 36628,
 '조직문화': 43733,
 '컨설팅': 50233,
 '사업장에': 22342,
 '교육법률': 6354,
 '전문가를': 41289,
 '매칭하여': 15153,
 '진단': 47049,
 '솔루션': 26548,
 '컨설팅내용': 50234,
 '내부': 9969,
 '규정': 7833,
 '개선방안': 1659,
 '제시': 42927,
 '피해지원': 52694,
 '기반강화': 8646,
 '피해지원기관과': 52695,
 '연대하여': 32264,
 '피해지원의': 52696,
 '공백': 4908,
 '분야': 21107,
 '사업내용': 22170,
 '기관': 8479,
 '종사자': 44040,
 '역량': 32058,
 '법률동행': 18834,
 '대응': 11960,
 '강화를': 1389,
 '워크숍': 34640,
 '사례연구회': 21986,
 '정책': 42614,
 '협력사업': 55045,
 '네트워크': 10164,
 '협의회': 55100,
 '정보화': 42350,
 '확산': 55612,
 '확산을': 55620,
 '개선': 1650,
 '대시민': 11919,
 '홍보캠페인': 55392,
 '진행': 47170,
 '관련': 5683,
 '여성폭력': 31982,
 '상담여성긴급전화': 23331,
 '아동여성폭력피해자': 30086,
 '통합지원센터': 51109,
 '폭력피해': 52295,
 '이주여성': 37121,
 '원스톱': 34719,
 '지원센터': 46401,
 '성폭력성폭행': 25658,
 '가정폭력': 716,
 '성매매': 25517,
 '학교폭력': 53221,
 '주의사항특이사항': 44744,
 '센터위치': 25950,
 '중구': 45255,
 '무교로': 15965,
 '더익스체인지서울빌딩': 12300,
 '서울직장성희롱성폭력예방센터': 24658,
 '관련법규': 5712,
 '서울특별시': 24681,
 '여성폭력방지와': 31984,
 '피해자보호': 52691,
 '지원에': 46423,
 '관한': 6016,
 '조례': 43478,
 '성동구': 25493,
 '반려동물': 17553,
 '무료상담실': 16013,
 '무료상담실무엇이든': 16014,
 '물어보시개': 16717,
 '월월': 34925,
 '이용대상': 36870,
 '성동구민': 25495,
 '누구나취약계층': 10824,
 '우선': 34173,
 '배정': 18479,
 '상담일정': 23347,
 '첫째': 48486,
 '셋째': 25959,
 '금요일': 8216,
 '사전예약': 22688,
 '전화': 41727,
 '사전': 22670,
 '상담': 23287,
 '상담시간': 23320,
 '이내약자': 36451,
 '수에': 27141,
 '조정': 43692,
 '상담분야': 23305,
 '건강상태': 2212,
 '이상행동': 36750,
 '초기': 48930,
 '행동교정': 54365,
 '간단한': 897,
 '육아': 35783,
 '진찰': 47159,
 '촉진': 49016,
 '수의학적': 27233,
 '부분의': 20599,
 '문제해결': 16495,
 '방향': 18329,
 '대처방법': 12051,
 '정밀검사': 42275,
 '필요': 52713,
 '여부': 31886,
 '기존에': 8959,
 '잘못': 39975,
 '알고': 30672,
 '있던': 39019,
 '교정': 6499,
 '취약계층': 49753,
 '등록의무': 13976,
 '대상개월령': 11822,
 '개이': 1790,
 '미등록된': 16857,
 '동물등록': 13148,
 '장소': 40149,
 '구청': 7168,
 '전문상담실': 41324,
 '서울시': 24451,
 '우리동네꼼꼼육아정보': 34122,
 '책자': 48155,
 '책자서울시와': 48162,
 '서울시육아종합지원센터는': 24536,
 '명의': 15493,
 '우리동네': 34121,
 '보육반장이': 19675,
 '직접': 47010,
 '발로': 17873,
 '뛰어': 14267,
 '수집한': 27353,
 '지역': 46181,
 '육아정보를': 35788,
 '꼼꼼': 9377,
 '육아정보': 35787,
 '책자를': 48161,
 '자치구마다': 39758,
 '종씩': 44053,
 '발간하였으며': 17754,
 '책자에는': 48163,
 '보육반장': 19674,
 '소개': 25977,
 '육아종합지원센터': 35789,
 '생애주기별': 23913,
 '대상별': 11841,
 '등이': 14077,
 '담겨': 11391,
 '있다': 39004,
 '책자는': 48158,
 '출생신고를': 49544,
 '동주민센터에': 13436,
 '방문하는': 18163,
 '출산부모에게': 49535,
 '전달': 41202,
 '예정이며': 33144,
 '자치구의': 39771,
 '열린육아방': 32536,
 '공동육아나눔터': 4742,
 '부모와': 20568,
 '아이들이': 30198,
 '자주': 39705,
 '찾는': 48021,
 '곳에': 4391,
 '배포할': 18564,
 '인터넷': 37712,
 '보육포털서비스': 19723,
 '서울시육아정보': 24534,
 '꼼꼼육아정보': 9378,
 '서울특별시육아종합지원센터양육지원': 24707,
 '우리동네보육반장': 34123,
 '우리동네육아지원': 34125,
 '반반택시': 17565,
 '심야시간': 29766,
 '동승앱': 13288,
 '심야': 29765,
 '택시수요': 50620,
 '대비': 11803,
 '택시공급': 50607,
 '부족으로': 20796,
 '발생하는': 17910,
 '승차난': 27774,
 '해소를': 54201,
 '목적으로': 15869,
 '규제': 7863,
 '샌드박스': 23796,
 '실증특례': 29633,
 '지정된': 46594,
 '개시': 1726,
 '개시일': 1728,
 '반반택시앱': 17566,
 '안드로이드폰에서만': 30412,
 '아이폰은': 30227,
 '어플': 31356,
 '시스템': 28357,
 '개발중': 1576,
 '개발': 1528,
 '일정': 38193,
 '미정': 16982,
 '방식': 18237,
 '동승을': 13289,
 '승객이': 27713,
 '앱을': 30883,
 '자동으로': 39317,
 '동승객동성을': 13283,
 '매칭하고': 15152,
 '운전자를': 34557,
 '호출하는': 55261,
 '과거': 5396,
 '운전자가': 34555,
 '승객을': 27711,
 '선택해서': 25086,
 '합승하는것과': 53977,
 '다른': 10993,
 '동승객': 13282,
 '매칭방법': 15148,
 '인접지역': 37600,
 '동승구간이': 13285,
 '동승시': 13287,
 '추가예상': 49295,
 '시간이': 27870,
 '이하인': 37204,
 '경우에만': 3579,
 '동성': 13269,
 '매칭': 15147,
 '남남': 9716,
 '여여': 31992,
 '운행지역': 34607,
 '구제': 7099,
 '샌드박스에서': 23797,
 '승차난이': 27775,
 '많이': 14830,
 '강남구': 1181,
 '서초구': 24765,
 '종로구': 43966,
 '용산구': 33985,
 '영등포구': 32624,
 '구로구': 6730,
 '광진구': 6182,
 '동작구': 13405,
 '관악구': 5958,
 '시간': 27828,
 '시시': 28371,
 '요금산정': 33790,
 '미터기': 17015,
 '요금': 33786,
 '이용거리에': 36849,
 '비례하여': 21594,
 '반반씩': 17564,
 '지불': 46090,
 '호출료': 55258,
 '천원은': 48373,
 '건당': 2267,
 '천원': 48370,
 '이용절차': 36953,
 '사전에': 22685,
 '승객기사': 27705,
 '신용체크카드': 29143,
 '등록': 13910,
 '인의': 37550,
 '앱에서': 30881,
 '동승': 13281,
 '요청': 33862,
 '이동경로가': 36484,
 '유사한': 35471,
 '동승구간': 13284,
 '추가': 49276,
 '예상시간': 33015,
 '경우에': 3574,
 '한정하여': 53739,
 '실시간': 29539,
 '택시기사에': 50610,
 '승객들은인인': 27706,
 '배정된': 18482,
 '좌석앞': 44180,
 '탑승': 50540,
 '최종': 49245,
 '목적지': 15880,
 '도착': 12943,
 '택시기사가': 50609,
 '하차': 53131,
 '승객의': 27712,
 '금액을': 8206,
 '입력하고': 38593,
 '승객간': 27704,
 '이동거리비율을': 36483,
 '계산하여': 3769,
 '요금플랫폼': 33801,
 '자동산정': 39313,
 '코나투스': 50273,
 '고객센터': 3983,
 '택시물류과': 50616,
 '이호상': 37267,
 '사회서비스원은': 22871,
 '무엇을': 16117,
 '하는': 52908,
 '곳인가요': 4403,
 '사회서비스': 22868,
 '분야에서': 21120,
 '공공부문의': 4564,
 '역할을': 32126,
 '강화하기': 1396,
 '서울시가': 24452,
 '설립한': 25210,
 '출연기관입니다': 49569,
 '국공립': 7336,
 '사회복지시설을': 22864,
 '운영하고': 34493,
 '종합재가센터를': 44139,
 '설치해서': 25408,
 '운영하며': 34502,
 '민간': 17052,
 '서비스기관에': 24229,
 '재무회계노무': 40511,
 '컨설팅을': 50237,
 '지원합니다': 46483,
 '자세한': 39499,
 '사항은': 22789,
 '사회서비스원': 22870,
 '홈페이지를': 55332,
 '참고하여': 47757,
 '주십시오': 44647,
 '주요문의사항': 44676,
 '더보기': 12294,
 '대표번호': 12127,
 '종료사업': 43994,
 'taxi': 189,
 '에스택시': 31752,
 '서울택시승차앱': 24676,
 '시범운영': 28186,
 '시범운영업무개요': 28188,
 '빈차를': 21789,
 '보고': 19323,
 '택시를': 50615,
 '기본적인': 8711,
 '기능을': 8571,
 '오프라인에서': 33312,
 '온라인까지': 33393,
 '확대하는': 55576,
 '개념을': 1490,
 '적용한': 41059,
 '선택운영기간': 25074,
 '종료앱': 43999,
 '구글': 6699,
 '다운받아': 11098,
 '서울택시': 24675,
 '공공승차': 4580,
 '시민승차': 28133,
 '등으로도': 14070,
 '검색가능': 2821,
 '기간': 8428,
 '기반의': 8660,
 '스마트폰만': 27581,
 '기타구분민간호출앱서울택시승차앱운영방식택시운수종사자의': 9079,
 '스마트폰택시결제기승차방식목적지를': 27586,
 '표출하여': 52424,
 '운전기사가': 34541,
 '고름시민이': 4084,
 '부르는': 20545,
 '택시운수종사자는': 50628,
 '별도의': 19197,
 '설치작업없이': 25370,
 '택시결제기를': 50606,
 '이용동의만': 36874,
 '거치면': 2166,
 '서울택시승차앱은': 24677,
 '전체': 41639,
 '적용': 40994,
 '보도자료': 19439,
 '장기요양': 40060,
 '이동지원서비스': 36502,
 '모두타': 15655,
 '돌봄택시': 13065,
 '이동지원서비스모두타': 36503,
 '보건복지부와': 19285,
 '서울시택시운송사업조합의': 24571,
 '민관협력사업으로': 17107,
 '거동이': 2028,
 '불편한': 21454,
 '어르신도': 31236,
 '방문을': 18145,
 '비롯한': 21598,
 '외출권을': 33735,
 '보장할': 19772,
 '시범사업': 28179,
 '시행': 28568,
 '코로나': 50282,
 '지속과': 46138,
 '운영자': 34460,
 '지속': 46132,
 '사유로': 22596,
 '일부로': 38033,
 '종료': 43984,
 '예정': 33122,
 '업무내용': 31507,
 '실제': 29622,
 '거주하는': 2137,
 '등급': 13837,
 '수급자': 26720,
 '시설급여를': 28257,
 '이용하지': 36988,
 '않은': 30657,
 '재가급여수급자': 40371,
 '휠체어': 56424,
 '유무와': 35451,
 '월토': 34963,
 '공휴일': 5386,
 '이용요금': 36924,
 '한도액': 53614,
 '시범사업기간': 28181,
 '동안': 13308,
 '본인부담금': 20251,
 '없음': 31689,
 '내에서': 10010,
 '자유롭게': 39636,
 '중형택시': 45538,
 '요금에': 33791,
 '서비스요금원': 24244,
 '기본요금': 8701,
 '거리당': 2053,
 '이용지역': 36961,
 '서울시내에서만': 24468,
 '가능시외운행': 316,
 '이용신청공단': 36907,
 '전용카드': 41529,
 '발급': 17788,
 '콜센터를': 50340,
 '통한': 51074,
 '배차예약': 18507,
 '차량이용': 47540,
 '확인을': 55675,
 '지참': 46676,
 '소재': 26367,
 '가까운': 291,
 '국민건강보험공단': 7400,
 '노인장기요양보험': 10419,
 '운영센터': 34421,
 '방문신청만': 18140,
 '원칙': 34795,
 '신체상태': 29394,
 '인지기능저하로': 37686,
 '본인이': 20265,
 '가족친족': 782,
 '대리': 11735,
 '가족친족이': 783,
 '없고': 31623,
 '독거인': 12970,
 '이해관계인': 37213,
 '신청불가': 29266,
 '공단지사': 4702,
 '영등포북부': 32636,
 '서초북부': 24782,
 '강남동부': 1186,
 '강남북부': 1188,
 '이동지원': 36501,
 '이용신청서': 36909,
 '개인정보': 1845,
 '수집이용': 27348,
 '제자': 43030,
 '동의서': 13338,
 '신분증': 29075,
 '추가서류': 49293,
 '가족관계를': 743,
 '확인할': 55702,
 '가족관계증명서': 747,
 '가족': 735,
 '친족': 50012,
 '외에': 33724,
 '신청하는': 29361,
 '이해관계인의': 37215,
 '위임장': 35168,
 '전용카드의': 41530,
 '월한도액은': 34968,
 '월말에': 34886,
 '소멸되어': 26088,
 '이월': 37007,
 '월중': 34952,
 '카드를': 50109,
 '발급받은': 17821,
 '시점부터': 28486,
 '말일까지': 14886,
 '잔액보다': 39952,
 '이용금액이': 36863,
 '많은': 14825,
 '초과되는': 48908,
 '전액': 41474,
 '문의에': 16405,
 '담당처': 11440,
 '상이': 23582,
 '예약센터': 33060,
 '예약관련': 33049,
 '제도': 42848,
 '국민건간보험공단': 7398,
 '부당요금': 20474,
 '승차거부': 27769,
 '여객자동차': 31805,
 '운수사업법과': 34332,
 '관련한': 5768,
 '택시불편신고는': 50618,
 '일반': 37854,
 '택시와': 50621,
 '동일하게': 13394,
 '취약가구': 49752,
 '중성화': 45357,
 '동물등록중성화': 13152,
 '지원구분': 46331,
 '동물돌봄의료서비스는': 13145,
 '반려동물의': 17557,
 '유기위험을': 35373,
 ...}

In [31]:
pd.DataFrame(dtm_tfidf.toarray(), columns=vocab)

,03월,08년,10,100명이상인,100세가,10만원,10만원상당,10명이고,10인승,10인의,...,힐링프로그램을,힐링하는,힐스테이트,힘들,힘들경우,힘들고,힘쓰고있습니다,힘쓴다,힘을,힘이
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2640,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2641,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2642,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2643,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2644,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [32]:
dist = np.sum(dtm_tfidf, axis=0)
pd.DataFrame(dist, columns=vocab).T.sort_values(by=0).tail(10)

               0
의한     15.021840
무엇입니까  15.270257
이상     15.577954
관한     16.593598
무엇인가요  16.650743
따라     16.652594
대한     18.866037
있나요    19.707343
서울시    22.586695
어떻게    37.924574

## 유사도 분석하기

문의 내용을 보면 비슷한 주제는 비슷한 위치체 놓인다. 따라서 벡터화된 텍스트의 거리를 측정하면 어떤 텍스트가 가까운 위치에 있는지를 계산할 수 있다. 문의 내용을 확인하고 등장 빈도에 기반해, 코사인 유사도 알고리즘 적용한다.

사이킷런은 코사인 유사도를 계산하는 기능을 제공한다. 코사인 유사도는 두 벡터 간의 각도의 코사인 값을 사용하여 두 벡터가 얼마나 같은 방향을 가리키고 있는지를 측정하는 유사도 지표이다.

In [33]:
from sklearn.metrics.pairwise import cosine_similarity

In [43]:
similarity_simple_pair = cosine_similarity(dtm_tfidf[0], dtm_tfidf)
result_list = similarity_simple_pair.tolist()[0]
result_list

[1.0000000000000002,
 0.0,
 0.009923678841957665,
 0.04840410811630889,
 0.020255740517537653,
 0.01854578524134521,
 0.007689200514538419,
 0.01852208319048694,
 0.004388306893623124,
 0.015596366271907504,
 0.006417818542155354,
 0.004801755890490625,
 0.022530745285606658,
 0.010670974912200707,
 0.005465729535177704,
 0.007180867167060437,
 0.0,
 0.007191459219804233,
 0.0,
 0.005548948853251886,
 0.0,
 0.014999956175567453,
 0.01346177710130625,
 0.03186585941980262,
 0.006324895844168201,
 0.011305577503097426,
 0.01042721964765217,
 0.0027107806748704246,
 0.02811621396063277,
 0.01945708490794608,
 0.009451308855535759,
 0.0,
 0.0,
 0.003921239868317877,
 0.03577777313658556,
 0.04603660879021193,
 0.0021097618250367593,
 0.002429415475842772,
 0.013110061818089973,
 0.014356080256311323,
 0.006058250439663021,
 0.0025792085469002564,
 0.006370413664274528,
 0.0026519404815570063,
 0.0,
 0.005011121517701414,
 0.002377621300635238,
 0.0,
 0.017201197098464488,
 0.005965951584532619,
 0.011601348999286984,
 0.01363253268224003,
 0.02210431523049338,
 0.019933621601035248,
 0.0,
 0.004632711582072988,
 0.014292086192621987,
 0.03813954956570752,
 0.007080456309906035,
 0.033279935029387225,
 0.023047854509065442,
 0.0032003012659737942,
 0.024660489405091038,
 0.016956403282390075,
 0.00148278554091606,
 0.00677717472453578,
 0.015109882005792299,
 0.0,
 0.0,
 0.01391065049233365,
 0.011879628596611489,
 0.0046442093171885895,
 0.016997659337466997,
 0.02772113767252716,
 0.010749435239885323,
 0.017207372905993487,
 0.010744533786529814,
 0.018966040563796457,
 0.004041336754264675,
 0.015769183316319168,
 0.01019029293987729,
 0.005664504671279328,
 0.009165690496140425,
 0.004786885266198996,
 0.029413161319371203,
 0.023812207224168984,
 0.005075155493417884,
 0.00886772148466521,
 0.014779349793597088,
 0.002604953896943588,
 0.0,
 0.032455847454716774,
 0.02368303942725988,
 0.005581900660934495,
 0.012341485192604496,
 0.005598180746312917,
 0.024274110932670408,
 0.03383797933567921,
 0.03520142432477841,
 0.0,
 0.00681356334906395,
 0.01308621291142944,
 0.007158313986901353,
 0.002790061909317132,
 0.01707458157925209,
 0.01961645503928455,
 0.019159364240582972,
 0.013702162584213386,
 0.005470754530320812,
 0.006130344972723275,
 0.015180697071320307,
 0.005179484960825761,
 0.009476062066163162,
 0.007230824634987451,
 0.01764444836020043,
 0.0,
 0.001072846364433847,
 0.017252263811122947,
 0.02080630527594711,
 0.007158860131966737,
 0.013413770755197809,
 0.018643218965239933,
 0.004274109029313336,
 0.00284244303824876,
 0.014846994081740346,
 0.03070517240936739,
 0.0022346938154343817,
 0.011917974367967534,
 0.01245165758468622,
 0.0,
 0.020320286451783985,
 0.011033539113292808,
 0.029791678983469787,
 0.01864783798333619,
 0.012665248360565654,
 0.0,
 0.0037941592749663124,
 0.0,
 0.007610221751564918,
 0.0,
 0.005650830449616826,
 0.04387292327046565,
 0.027753077533713005,
 0.01340910451395548,
 0.00948249833147206,
 0.0,
 0.00991209899889523,
 0.011152509701747982,
 0.007467384755985429,
 0.0024619302588723526,
 0.010895995695894934,
 0.011010196374813918,
 0.0,
 0.022978609107453855,
 0.0030655112985572327,
 0.04628021242289674,
 0.015167500085687749,
 0.013072371468421082,
 0.0074033410862533715,
 0.008992017372341607,
 0.004652735744920952,
 0.004540443761158435,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.017873180965505338,
 0.038562928331589,
 0.006065742490656894,
 0.007213251850984028,
 0.0,
 0.0,
 0.04303360725152773,
 0.0,
 0.0,
 0.0,
 0.0,
 0.006789917258224286,
 0.0,
 0.0,
 0.0,
 0.0,
 0.007042091460869243,
 0.0,
 0.004012147943998043,
 0.0,
 0.0,
 0.0,
 0.0,
 0.00780961156733195,
 0.0,
 0.0,
 0.022489173755518323,
 0.0047432093491794475,
 0.01658823458743902,
 0.009140245251321937,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0189731163812408,
 0.0,
 0.0,
 0.007803000633168973,
 0.0202062243236484,
 0.0,
 0.00727686010420016,
 0.010547569299789436,
 0.0044375980454984835,
 0.024896167552853617,
 0.0,
 0.005857908034222725,
 0.007372929738901779,
 0.024441330595209934,
 0.0,
 0.0,
 0.012941928301227423,
 0.015241048796369975,
 0.03041976467564507,
 0.0,
 0.017968686399921684,
 0.0,
 0.013979133872250254,
 0.016600372794748797,
 0.0,
 0.011130071289613686,
 0.003470568057049424,
 0.0,
 0.0,
 0.0054767515325919326,
 0.04194484159858852,
 0.0,
 0.0,
 0.0,
 0.0036890013014219893,
 0.005494464137723934,
 0.0,
 0.0,
 0.0,
 0.013235378598420056,
 0.031939587703746594,
 0.0,
 0.01716563106894526,
 0.0,
 0.0,
 0.0,
 0.003350632260659393,
 0.007075763333323969,
 0.019371584954453416,
 0.005141549202629282,
 0.0,
 0.0,
 0.0,
 0.004654130978102516,
 0.0029829528557277535,
 0.00716345485175801,
 0.0,
 0.004444029632697927,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.013129628375186459,
 0.0,
 0.004962941455550965,
 0.0,
 0.0,
 0.0,
 0.0,
 0.006273063208789585,
 0.002832166332728741,
 0.0,
 0.0,
 0.018992713053847275,
 0.027557498062747654,
 0.009673671518449608,
 0.0,
 0.01730547437937383,
 0.009466146908335528,
 0.0,
 0.009426660160978529,
 0.0,
 0.0,
 0.0,
 0.0163611715509548,
 0.006928794021700763,
 0.010725808378906696,
 0.0,
 0.019051457801029733,
 0.0,
 0.0,
 0.020001601161367386,
 0.006483145848608364,
 0.019342793109887874,
 0.010896613694749799,
 0.0,
 0.010726136336710978,
 0.004827608060727692,
 0.003837174829284061,
 0.0,
 0.0,
 0.0,
 0.0,
 0.02963257285390252,
 0.006673142795545353,
 0.012418093651350447,
 0.016776795013885536,
 0.008923766801386825,
 0.010484722992510413,
 0.003376624483283912,
 0.01054047183496422,
 0.0,
 0.00617656345935442,
 0.009547337497536848,
 0.0,
 0.0,
 0.004076389120289965,
 0.002134968437823925,
 0.0,
 0.008224156585507156,
 0.016119554249382655,
 0.0,
 0.0,
 0.0,
 0.004608802228741098,
 0.017968340173081833,
 0.0066377499809206295,
 0.024697873298718944,
 0.0,
 0.0,
 0.011033739743107684,
 0.0,
 0.0,
 0.0,
 0.016294099054143245,
 0.008520570462848502,
 0.0,
 0.0,
 0.002139425203346302,
 0.0,
 0.0,
 0.0,
 0.0,
 0.005185289947358726,
 0.0,
 0.0,
 0.0,
 0.006023411845044275,
 0.0030997334884165185,
 0.011163160562974795,
 0.00882254446778873,
 0.014159863277370788,
 0.02523151120992176,
 0.0,
 0.003851720352463159,
 0.0,
 0.0027573895987602973,
 0.016928574970466216,
 0.0,
 0.0,
 0.0,
 0.0,
 0.017079597426749842,
 0.020048890991951163,
 0.0,
 0.010301390777202796,
 0.0,
 0.012365455880442721,
 0.008586796995001944,
 0.0,
 0.0,
 0.011749892593611994,
 0.0044378778568185916,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.01298124781151468,
 0.017958756968879712,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.014127358670561106,
 0.00685231375951276,
 0.005300155577463322,
 0.014403496402442154,
 0.0,
 0.0,
 0.0060302467117562646,
 0.003885633724262714,
 0.00848892785587462,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.006361894460940815,
 0.0,
 0.0,
 0.0,
 0.004383888023529117,
 0.0,
 0.015110141855412967,
 0.00636447159558961,
 0.0,
 0.0,
 0.02747652326861747,
 0.0,
 0.0,
 0.0,
 0.003281394677971422,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.005488811373632721,
 0.0,
 0.0,
 0.0,
 0.00688886216206958,
 0.014999956175567453,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.006553695672265486,
 0.0,
 0.007871075906443576,
 0.0,
 0.007549486258900094,
 0.0,
 0.0,
 0.011560881090539465,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.015194718866496825,
 0.0,
 0.0,
 0.0,
 0.01663631476166407,
 0.0,
 0.0,
 0.0,
 0.0,
 0.020255982913529567,
 0.0,
 0.0,
 0.027803848334372508,
 0.0,
 0.0,
 0.007196009620687413,
 0.0,
 0.0,
 0.0,
 0.003913413633002456,
 0.0,
 0.00855550683112603,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.007450827767629356,
 0.0,
 0.006433178911419985,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.004430618601197043,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.005813862827097472,
 0.0,
 0.0,
 0.0,
 0.006317082235829221,
 0.006317082235829221,
 0.00637027584650769,
 0.0,
 0.0,
 0.0,
 0.0,
 0.007078613479707072,
 0.0,
 0.0,
 0.0,
 0.031432990906132684,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.004426784506798858,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.004046200729910744,
 0.0,
 0.0519518674464641,
 0.0,
 0.0,
 0.0,
 0.0,
 0.009555138349827517,
 0.0,
 0.00749799944868342,
 0.003939191969300749,
 0.0,
 0.01868575390253408,
 0.0,
 0.0,
 0.0062832704677715946,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.012293740095381287,
 0.0,
 0.0,
 0.0104169580018609,
 0.0,
 0.010988915689723724,
 0.0,
 0.0,
 0.0,
 0.007531011783819044,
 0.0,
 0.0,
 0.003568944563225506,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.031058943347500815,
 0.0,
 0.0,
 0.0,
 0.01156764826605896,
 0.0,
 0.008382876824324677,
 0.009657752846939793,
 0.0,
 0.008079833429331766,
 0.007695768472797397,
 0.01926595668812498,
 0.009351871328259041,
 0.0,
 0.004755305246135131,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.010113966035830722,
 0.0,
 0.0,
 0.0,
 0.009028294883503468,
 0.004729284575956495,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0037972474369525645,
 0.00933821949098371,
 0.0,
 0.0,
 0.004971664157026243,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.01092308207418929,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.003419799436418672,
 0.0,
 0.0,
 0.004105846760160894,
 0.005129876953244504,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0013866179061663578,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.010646786479301038,
 0.0,
 0.0,
 0.0030281332064449563,
 0.0,
 0.0,
 0.005826450507475706,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.004986428271494237,
 0.0,
 0.003563322333061374,
 0.0,
 0.0,
 0.0047267537012741475,
 0.0,
 0.0,
 0.004771353376478744,
 0.0,
 0.0,
 0.0,
 0.01726829771787866,
 0.018615302446775363,
 0.0,
 0.004901316376200581,
 0.003507416339171291,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.017421747238560197,
 0.0,
 0.005048252647420681,
 0.0,
 0.014329085037900377,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0109742158267745,
 0.0,
 0.01025620880808195,
 0.004555318622450284,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.012118877731460738,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0033054169580190905,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.00492360517166871,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0157665685119659,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.00761012667299305,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.003892947003907453,
 0.0,
 0.0,
 0.011906884066171266,
 0.013627876917797857,
 0.004771290505069179,
 0.0,
 0.0,
 0.015346470999247628,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.003945294172363302,
 0.0,
 0.0,
 0.0,
 0.005217780699516877,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.010310303149052033,
 0.01836603477829248,
 0.0,
 0.0,
 0.0,
 0.009631087570443599,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0058813683255266,
 0.0,
 0.0036218666433653532,
 0.0061877435027882,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.00569049102857446,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.056151851948294154,
 0.0,
 0.004407825739110964,
 0.0,
 0.0,
 0.01093138631430296,
 0.0,
 0.0,
 0.0,
 0.006102571041497075,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.024844823915495303,
 0.0,
 0.0016499195942505777,
 0.0070138456095552295,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.014430770691942714,
 0.012459822329677326,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.00528440915792527,
 0.005916764895010081,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.01046003403809262,
 0.0037829538059271813,
 0.0,
 0.0,
 0.0,
 0.0061283390180363094,
 0.005632694742891816,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.015060268965837363,
 0.004067883010490983,
 0.009682925034535422,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.014500176977005966,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.002408683123935832,
 0.0,
 0.022426044739384195,
 0.008925681641002532,
 0.0069253292080037835,
 0.0,
 0.0,
 0.01203719433862539,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.010637558724019367,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.005279248988727696,
 0.0,
 0.0,
 0.0,
 0.0,
 0.021608611359082715,
 0.0,
 0.0,
 0.0,
 0.0,
 0.006018728888552716,
 ...]

result_list를 '유사도' 파생 변수로 생성하고 유사도가 높은 순으로 정렬한다.  
유사도가 높은 문서는 거리가 가깝다고 불 수 있으므로, 이 방법을 응용하면 문의에 대한 비슷한 질문을 추천해 보여주는 등과 같이 활용할 수 있다.

In [47]:
df['유사도'] = result_list
df.sort_values(by='유사도', ascending=False).head(10)

,번호,분류,제목,내용,내용번호,문서,유사도
0,2645,복지,아빠 육아휴직 장려금,아빠 육아휴직 장려금 업무개요 남성근로자의 육아휴직을 장려하고 양육에 따른 경...,23522464,아빠 육아휴직 장려금 아빠 육아휴직 장려금 업무개요 남성근로자의 육아휴직을 장...,1.000000
1772,873,경제,도시계획시설부지 재결신청 이후 진행단계는 어떤 과정을 거칩니까?,도시계획시설부지 재결신청 이후 진행단계는 어떤 과정을 거칩니까재결신청 이후 재결신청...,2897109,도시계획시설부지 재결신청 이후 진행단계는 어떤 과정을 거칩니까? 도시계획시설부지 재...,0.057158
850,1795,경제,주민대표회의 구성원 몇명입니까?,주민대표회의 구성원 몇명입니까인이상 인 이하로 구성합니다,2896070,주민대표회의 구성원 몇명입니까? 주민대표회의 구성원 몇명입니까인이상 인 이하로 구성합니다,0.056152
539,2106,행정,행려자도 아니고 시설수용자도 아닌 사람이 살고 있던 비닐하우스에서 화상을 입었습니다...,행려자도 아니고 시설수용자도 아닌 사람이 살고 있던 비닐하우스에서 화상을 입었습니다...,2896135,행려자도 아니고 시설수용자도 아닌 사람이 살고 있던 비닐하우스에서 화상을 입었습니다...,0.051952
3,2642,복지,"광진맘택시 운영(임산부,영아 양육가정 전용 택시)",광진맘택시 운영임산부영아 양육가정 전용 택시 업무개요 교통약자인 임산부와 영아가정...,22904492,"광진맘택시 운영(임산부,영아 양육가정 전용 택시) 광진맘택시 운영임산부영아 양육가정...",0.048404
155,2490,경제,[농업기술센터] 후계농업경영인 선정 및 청년창업형 후계농업경영인 신청 안내,농업기술센터 후계농업경영인 선정 및 청년창업형 후계농업경영인 신청 안내 업무...,2896492,[농업기술센터] 후계농업경영인 선정 및 청년창업형 후계농업경영인 신청 안내 농업기술...,0.046280
35,2610,행정,[시ㆍ구정외 타기관 관련 상담] 고용노동부 [일자리 안정자금],시구정외 타기관 관련 상담 고용노동부 일자리 안정자금 최저임금 해결사 일자리 안정자...,14425328,[시ㆍ구정외 타기관 관련 상담] 고용노동부 [일자리 안정자금] 시구정외 타기관 관련...,0.046037
141,2504,경제,[농업기술센터] 도시농업전문가양성교육 신청,농업기술센터 도시농업전문가양성교육 신청 업무개요 도시농업육성 및 지원에 관한 법...,2897619,[농업기술센터] 도시농업전문가양성교육 신청 농업기술센터 도시농업전문가양성교육 신청 ...,0.043873
174,2471,행정,찾아가는 아버지교실,찾아가는 아버지교실 업무개요 아버지와 자녀 간 공감대 형성을 통해 가족...,2898611,찾아가는 아버지교실 찾아가는 아버지교실 업무개요 아버지와 자녀 간 공감...,0.043034
233,2412,경제,[농업기술센터] 귀농창업 평일반 교육 신청,농업기술센터 귀농창업 평일반 교육 신청 업무개요 서울시민을 대상으로 귀농창업...,2898211,[농업기술센터] 귀농창업 평일반 교육 신청 농업기술센터 귀농창업 평일반 교육 신청 ...,0.041945

# 순환 신경망으로 텍스트 분류하기

순환 신경망(Recurrent Neural Network, RNN)은 이름에서 알 수 있듯이 신경망을 사용해 모델링한다. 순환 신경망의 가장 큰 특징은 이전 단어가 다음 단어에 의존 관계를 지닐 수 있도록 시퀀스 형태로 입력된다는 것이다.

## 데이터 불러오기

In [48]:
df = pd.read_csv('./data/seoul-120-text.csv')
df.shape

(2645, 5)

In [49]:
df['문서'] = df['제목'] + ' ' + df['내용']
df.head()

,번호,분류,제목,내용,내용번호,문서
0,2645,복지,아빠 육아휴직 장려금,아빠 육아휴직 장려금 업무개요 남성근로자의 육아휴직을 장려하고 양육에 따른 경...,23522464,아빠 육아휴직 장려금 아빠 육아휴직 장려금 업무개요 남성근로자의 육아휴직을 장...
1,2644,경제,[서울산업진흥원] 서울메이드란?,서울산업진흥원 서울메이드란 서울의 감성을 담은 다양하고 새로운 경험을 제공하기 위해...,23194045,[서울산업진흥원] 서울메이드란? 서울산업진흥원 서울메이드란 서울의 감성을 담은 다양...
2,2643,환경,(강북구) 정비중,강북구 정비중 업무개요 투명 폐트병을 교환보상하므로 수거율을 높이고 폐기물을 감...,23032485,(강북구) 정비중 강북구 정비중 업무개요 투명 폐트병을 교환보상하므로 수거율을 ...
3,2642,복지,"광진맘택시 운영(임산부,영아 양육가정 전용 택시)",광진맘택시 운영임산부영아 양육가정 전용 택시 업무개요 교통약자인 임산부와 영아가정...,22904492,"광진맘택시 운영(임산부,영아 양육가정 전용 택시) 광진맘택시 운영임산부영아 양육가정..."
4,2641,복지,마포 뇌병변장애인 비전센터,마포 뇌병변장애인 비전센터 마포뇌병변장애인 비전센터 운영 구분 내용 목적 학...,22477798,마포 뇌병변장애인 비전센터 마포 뇌병변장애인 비전센터 마포뇌병변장애인 비전센터 운영...

In [50]:
df.분류.value_counts()

분류
행정        1098
경제         823
복지         217
환경         124
주택도시계획     110
문화관광        96
교통          90
안전          51
건강          23
여성가족        13
Name: count, dtype: int64

행정의 빈도수와 건강, 여성가족의 빈도수 차이가 심하다. 분류별 빈도수 값이 불균형이 심할 경우 전체 데이터로 예측하면 성능이 떨어질 수 있으므로, 언더샘플링이나 오버샘플링으로 정답값을 균형있게 만들어 주기도 한다. 여기에서는 상위 데이터 세 개만 사용해 분석한다. 이렇게 일부 분류만 사용하더라도 정답에 불균형이 있기 때문에 빈도가 많은 분류의 예측 정확도가 더 높게 나올 것이다.

df 데이터프레임의 '분류' 열에는 10종류의 분류가 있는데 '행정', '경제', '복지'만 추출하려면 아래와 같이 OR(|) 연산자를 사용하면 된다.  
`df[(df.분류 == '행정') | (df.분류 == '경제') | (df.분류 == '복지')]`  
하지만 추출하려는 열이 매우 많다면 OR(|) 연산자를 사용하면 코드가 많이 길어진다. 이럴 경우 `isin()` 메소드를 사용하면 논리식에 `in` 연산자를 사용하는 것과 같은 효과를 낼 수 있다.

In [64]:
df = df[df.분류.isin(['행정', '경제', '복지'])]
df.shape

(2138, 6)

In [65]:
df.head()

,번호,분류,제목,내용,내용번호,문서
0,2645,복지,아빠 육아휴직 장려금,아빠 육아휴직 장려금 업무개요 남성근로자의 육아휴직을 장려하고 양육에 따른 경...,23522464,아빠 육아휴직 장려금 아빠 육아휴직 장려금 업무개요 남성근로자의 육아휴직을 장...
1,2644,경제,[서울산업진흥원] 서울메이드란?,서울산업진흥원 서울메이드란 서울의 감성을 담은 다양하고 새로운 경험을 제공하기 위해...,23194045,[서울산업진흥원] 서울메이드란? 서울산업진흥원 서울메이드란 서울의 감성을 담은 다양...
3,2642,복지,"광진맘택시 운영(임산부,영아 양육가정 전용 택시)",광진맘택시 운영임산부영아 양육가정 전용 택시 업무개요 교통약자인 임산부와 영아가정...,22904492,"광진맘택시 운영(임산부,영아 양육가정 전용 택시) 광진맘택시 운영임산부영아 양육가정..."
4,2641,복지,마포 뇌병변장애인 비전센터,마포 뇌병변장애인 비전센터 마포뇌병변장애인 비전센터 운영 구분 내용 목적 학...,22477798,마포 뇌병변장애인 비전센터 마포 뇌병변장애인 비전센터 마포뇌병변장애인 비전센터 운영...
5,2640,행정,2021년도 중1·고1 신입생 입학준비금 지원,년도 중고 신입생 입학준비금 지원 업무개요 서울시는 전국 최초로 년도부터 개 자...,22227896,2021년도 중1·고1 신입생 입학준비금 지원 년도 중고 신입생 입학준비금 지원 ...

## 학습 데이터셋과 테스트 데이터셋 분리하기

데이터프레임에서 독립 변수(문제, x_data)와 종속 변수(정답, y_data)를 추출한다.

In [77]:
x_data, y_data = df.문서, df.분류
# print(x_data, y_data)

## 레이블 값을 원-핫 인코딩하기

get_dummies() 메소드를 사용해서 레이블값을 0과 1로 이루어진 행렬 형태로 만든다. 이를 원-핫 인코딩(One-Hot Encoding)이라고 하는데 데이터를 0과 1로 구별한다. 고유값에 해당되는 단어는 1(True), 나머지는 0(False)으로 만드는 방식으로, 사이킷런 머신러닝 알고리즘에는 문자열값을 넣을 수 없기 때문에 숫자형으로 인코딩한 뒤 학습시키기 위해서이다.

In [83]:
y_onehot = pd.get_dummies(y_data, dtype=int)
y_onehot.head()

   경제  복지  행정
0   0   1   0
1   1   0   0
3   0   1   0
4   0   1   0
5   0   0   1

데이터프레임에서 추출된 독립 변수와 종속 변수를 학습 데이터셋과 테스트 데이터셋으로 나누기 위해서 train_test_split를 import 한다.

In [84]:
from sklearn.model_selection import train_test_split

train_test_split() 함수는 독립 변수(x_data), 원-핫 인코딩된 종속 변수(y_onehot) 학습 데이터셋 80%, 테스트 데이터셋 20%의 비율로 분할한다. 이때, 재현성을 유지하기 위해 random_state를 지정했고 층화 추출을 수행하기 위해 stratify를 지정했다.  
층화 추출이란 종속 변수에 저장된 각 클래스의 비율을 계산해서 분할된 학습 데이터셋과 테스트 데이터셋에서 그 클래스 비율이 원본 비율과 동일하게 유지한다.

In [86]:
x_train, x_test, y_train, y_test = train_test_split(x_data, y_onehot, train_size=0.8, random_state=42, stratify=y_onehot)
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(1710,) (428,) (1710, 3) (428, 3)

y_train, y_test의 값을 확인해 보면 원-핫 인코딩된 결과 즉, 0과 1로 이루어진 희소 행렬 형태로 이루어진 것을 확인할 수 있다.  
데이터셋을 나누다 보면 특정 분류는 학습 데이터셋에 많고, 테스트 데이터셋에는 너무 적어 균형있게 학습하지 못하는 현상이 발생되기도 한다. 이를 방지하기 위해 train_test_split() 함수로 데이터셋을 나눌 때 stratify 속성에 독립 변수(정답) 지정하면 학습 데이터셋과 테스트 데이터셋의 정답 비율을 맞춰서 나눠준다. 다음 코드를 실행해 보면 '경제', '복지', '행정'의 정답 비율이 비슷한 비율로 나뉘 것을 확인할 수 있다.

In [92]:
print(y_train.mean())
print(y_test.mean())

경제    0.384795
복지    0.101754
행정    0.513450
dtype: float64
경제    0.385514
복지    0.100467
행정    0.514019
dtype: float64

## 벡터화하기

토큰화하기  
토크나이저는 텍스트를 여러개의 토큰으로 나눈다. 케라스의 Tokenizer 클래스를 사용하면 각 텍스트를 일련의 정수(정수는 단어 사전의 토큰 인덱스) 또는 단어수에 따라 각 토큰의 계사가 이진일 수 있는 벡터로 변환해 테스트 데이터를 벡터화(Vectorization)할 수 있다.

시퀀스 만들기  
Tokenizer는 데이터에 출현하는 모든 단어의 계수를 세고 빈도수를 정렬해서 num_words 속성에 지정된 만큼만 숫자로 반환한다.

In [93]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [118]:
# 모델의 복잡도를 제어하고 메모리를 효율적으로 사용하기 위해서 데이터셋에 고유한 단어가 아무리 많아도 빈도수가 높은 상위 10,000개의 단어만 사용한다는 설정이다.
vocab_size = 10000
# Out-Of-Vocabulary(단어 사전에 없는 단어)를 처리할 특별 토큰을 지정한다.
# 단어 사전에 포함되지 않은(상위 10,000개에 못 든) 생소한 단어를 만나면 '<oov>'라는 고정된 값으로 치환한다. 이 처리를 하지 않으면 단어 사전에 포함되지 않은
# 단어는 그냥 삭제되어 문장의 길이가 변하거나 문맥이 왜곡될 수 있다.
tokenizer = Tokenizer(num_words=vocab_size, oov_token='<oov>')
tokenizer

fit_on_texts() 메소드에 학습 데이터를 넘겨서 tensorflow의 Tokenizer를 학습시킨다.  
학습 결과는 단어와 인덱스가 key와 value로 구성된 딕셔너리를 생성하고 영문자인 경우 자동으로 소문자로 변환해서 반환되며, 느낌표나 마침표 같은 구두점은 자동으로 제거한다.

In [119]:
tokenizer.fit_on_texts(x_train)

word_index 속성으로 단어와 인덱스가 key, value로 이루어진 딕셔너리를 얻어온다.

In [125]:
print(tokenizer.word_index)

{'<oov>': 1, '및': 2, '돋움': 3, '수': 4, '경우': 5, '또는': 6, '등': 7, '있는': 8, '년': 9, '월': 10, '있습니다': 11, '어떻게': 12, '서울시': 13, '후': 14, '중': 15, '일': 16, '홈페이지': 17, '대한': 18, '그': 19, '따라': 20, '의한': 21, '위한': 22, '가능': 23, '이상': 24, '하는': 25, '관한': 26, '할': 27, '경우에는': 28, '있나요': 29, '등을': 30, '합니다': 31, '각': 32, '층': 33, '문의': 34, '시': 35, '위하여': 36, '신청': 37, '관련': 38, '있음': 39, '지원': 40, '등의': 41, '규정에': 42, '확인': 43, '개': 44, '운영': 45, '제조': 46, '필요한': 47, '됩니다': 48, '따른': 49, '내용': 50, '무엇인가요': 51, '무엇입니까': 52, '것': 53, '해당': 54, '어떤': 55, '하나요': 56, '통해': 57, '원': 58, '하고': 59, '등에': 60, '되나요': 61, '함': 62, '주소': 63, '교육': 64, '명': 65, '기타': 66, '서울특별시': 67, '이상의': 68, '위해': 69, '구분': 70, '안내': 71, '있으며': 72, '내': 73, '이용': 74, '대하여': 75, '공무원': 76, '회': 77, '어린이집': 78, '만원': 79, '시간': 80, '프로그램': 81, '평일': 82, '서울': 83, '말한다': 84, '당해': 85, '자': 86, '다른': 87, '없는': 88, '접수': 89, '직접': 90, '인': 91, '한': 92, '단': 93, '한다': 94, '기타사항': 95, '사업': 96, '건축물': 97, '있도록': 98, '업무개요': 99, '동': 100, '해당하는': 101, '상담': 102, '다만': 103, '모든': 104, '말합니다': 105, '이하': 106, '건축물의': 107, '시설': 108, '청소년': 109, '발급': 110, '기준': 111, '의하여': 112, '대상': 113, '가능합니다': 114, '분': 115, '호선': 116, '제외': 117, '의거': 118, '번지': 119, '번': 120, '신고': 121, '전화번호': 122, '이': 123, '이후': 124, '시시': 125, '제공': 126, '현재': 127, '장애인': 128, '반드시': 129, '변경': 130, '것을': 131, '포함': 132, '농업기술센터': 133, '제출': 134, '중구': 135, '신청서': 136, '아니한': 137, '방법': 138, '이를': 139, '함께': 140, '자본금은': 141, '없음': 142, '시행령': 143, '해야': 144, '사항은': 145, '각종': 146, '위치': 147, '받은': 148, '지급': 149, 'amp': 150, '등으로': 151, '설치': 152, '인터넷': 153, '입니다': 154, '되어': 155, '서비스': 156, '신청방법': 157, '사용': 158, '가능한': 159, '대상으로': 160, '것으로': 161, '거쳐': 162, '이상인': 163, '검색': 164, '목적으로': 165, '부': 166, '모집': 167, '작성': 168, '하며': 169, '총': 170, '서울시청': 171, '하여야': 172, '공동주택': 173, '알고': 174, '또한': 175, '대해': 176, '호': 177, '바랍니다': 178, '등이': 179, '있다': 180, '공무원은': 181, '토지': 182, '아파트': 183, '것이': 184, '않은': 185, '제조에': 186, '설치하는': 187, '서대문구': 188, '에': 189, '같은': 190, '정하는': 191, '다운로드': 192, '부터': 193, '급': 194, '경우는': 195, '전화': 196, '등록': 197, '경우에': 198, '받을': 199, '않는': 200, '있는지': 201, '의해': 202, '것입니다': 203, '미만': 204, '제조의': 205, '차': 206, '다양한': 207, '자치구': 208, '업무내용': 209, '세': 210, '담당자': 211, '연락처': 212, '도로': 213, '은평구': 214, '주요': 215, '온라인': 216, '이메일': 217, '의': 218, '로': 219, '관리': 220, '되는': 221, '불가': 222, '다음의': 223, '이내': 224, '무료': 225, '구청': 226, '아닌': 227, '가': 228, '여부': 229, '지역': 230, '어디서': 231, '받고': 232, '업무': 233, '를': 234, '이에': 235, '적용': 236, '지하철': 237, '만': 238, '정보': 239, '하지': 240, '없습니다': 241, '주택': 242, '주택을': 243, '하면': 244, '방문': 245, '기술능력과': 246, '세대': 247, '제': 248, '구': 249, '서울의': 250, '자세한': 251, '다음': 252, '규정하고': 253, '통한': 254, '있습니까': 255, '대상자': 256, '전': 257, '법률': 258, '사항': 259, '대': 260, '디자인': 261, '받아': 262, '받아야': 263, '번출구': 264, '약': 265, '있고': 266, '관련된': 267, '기': 268, '운영하고': 269, '어느': 270, '연결': 271, '있을': 272, '때': 273, '주차장': 274, '아래와': 275, '지원하는': 276, '것은': 277, '별도': 278, '기준으로': 279, '공무원의': 280, '관할': 281, '구비서류': 282, '개월': 283, '볼': 284, '의료급여': 285, '언제': 286, '마포구': 287, '기준은': 288, '문화': 289, '주': 290, '매주': 291, '참여': 292, '실시': 293, '공사': 294, '사본': 295, '공무원이': 296, '방법은': 297, '모두': 298, '홈페이지에서': 299, '선정': 300, '현황': 301, '계획': 302, '대하여는': 303, '매년': 304, '있어': 305, '없이': 306, '사용할': 307, '송파구': 308, '에서': 309, '어디에': 310, '시설을': 311, '않음': 312, '있으므로': 313, '면적': 314, '본인이': 315, '허가': 316, '콜센터': 317, '서울시에서': 318, '때에는': 319, '대표자': 320, '건축': 321, '말하며': 322, '내용을': 323, '싶은데': 324, '조성': 325, '정한': 326, '종로구': 327, '가능한가요': 328, '앞': 329, '억원': 330, '분의': 331, '건축하는': 332, '도로에': 333, '학교': 334, '행사': 335, '하여': 336, '종류는': 337, '통하여': 338, '처리': 339, '입주자': 340, '일금': 341, '예정': 342, '으로': 343, '천만원': 344, '문의처': 345, '된': 346, '서류': 347, '팩스': 348, '매월': 349, '조례': 350, '이내에': 351, '법': 352, '행정처분': 353, '가지고': 354, '연면적': 355, '가능함': 356, '다시': 357, '이용에': 358, '까지': 359, '신청기간': 360, '찾아가는': 361, '필요하다고': 362, '됨': 363, '아이조아': 364, '밖에': 365, '미만인': 366, '됩니까': 367, '기존': 368, '사업의': 369, '인한': 370, '시간외': 371, '예약': 372, '같이': 373, '확인할': 374, '행위를': 375, '사항을': 376, '싶습니다': 377, '관내': 378, '몇': 379, '무엇이': 380, '토요일': 381, '방문하여': 382, '진행': 383, '받지': 384, '시민': 385, '단체': 386, '경로': 387, '누구나': 388, '아니하는': 389, '활용': 390, '일월': 391, '일요일': 392, '심의를': 393, '범위': 394, '장소': 395, '조합원': 396, '수립': 397, '치매지원센터': 398, '미터': 399, '당직실': 400, '통': 401, '타': 402, '후에': 403, '위': 404, '따라서': 405, '별표': 406, '건설기술자': 407, '업무설명': 408, '제곱미터': 409, '발송': 410, '사업을': 411, '시행': 412, '쓰이는': 413, '운영시간': 414, '바로가기': 415, '어린이': 416, '건축법': 417, '용산구': 418, '이전': 419, '소재': 420, '개소': 421, '추가': 422, '많은': 423, '편의시설': 424, '국가': 425, '의견을': 426, '공고': 427, '절차': 428, '출구': 429, '열람': 430, '작성하여': 431, '사회단체보조금': 432, '내에서': 433, 'ㅇ': 434, '구성되어': 435, '않습니다': 436, '이상이고': 437, '용도에': 438, '금': 439, '사전에': 440, '소속': 441, '팀': 442, '성동구': 443, '인당': 444, '인하여': 445, '본인': 446, '주택의': 447, '더': 448, '전에': 449, '이하의': 450, '규정': 451, '도시': 452, '절차는': 453, '추진': 454, '담당부서': 455, '대지에': 456, '학부모': 457, '지정하는': 458, '먼저': 459, '결정': 460, '깊은': 461, '관심에': 462, '계속': 463, '이용할': 464, '업무를': 465, '검토': 466, '결제': 467, '않고': 468, '제호': 469, '개요': 470, '년간': 471, '함은': 472, '신용카드': 473, '설치된': 474, '주거이전비': 475, '카드': 476, 'apos': 477, '선택': 478, '일화': 479, '초등학교': 480, '같습니다': 481, '이와': 482, '운영하는': 483, '일수': 484, '한하여': 485, '정하여': 486, '일반': 487, '홈페이지를': 488, '대상은': 489, '을': 490, '신청을': 491, '있지': 492, '공휴일': 493, '보건소': 494, '임대주택': 495, '광진구': 496, '영등포구': 497, '개인': 498, '하는데': 499, '유사한': 500, '월월': 501, '일정': 502, '별도의': 503, '내용은': 504, '등록을': 505, '높이': 506, '제항': 507, '오전': 508, '진료비': 509, '될': 510, '공동주택의': 511, '접한': 512, '권': 513, '합계가': 514, '우선': 515, '강': 516, '사례': 517, '건축물이': 518, '로그인': 519, '실시하는': 520, '시스템': 521, '전국': 522, '이는': 523, '구성': 524, '회의': 525, '정원': 526, '경우에도': 527, '바에': 528, '회원': 529, '사업으로': 530, '서울시의': 531, '취소': 532, '부동산': 533, '필요': 534, '전체': 535, '거리': 536, '동법': 537, '하는지': 538, '동일': 539, '관하여': 540, '최대': 541, '알': 542, '받을수': 543, '한함': 544, '미술작품': 545, '교육을': 546, '급식': 547, '강남구': 548, '다음과': 549, '다': 550, '자료를': 551, '선착순': 552, '포함한': 553, '자가': 554, '본인의': 555, '제항의': 556, '참조': 557, '밖의': 558, '조치를': 559, '고시하는': 560, '기준에': 561, '실시하고': 562, '얻어': 563, '체험': 564, '위원회': 565, '자격': 566, '서초구': 567, '도봉구': 568, '건축물을': 569, '감사합니다': 570, '등은': 571, '행동강령': 572, '지원을': 573, '조합의': 574, '심의': 575, '외': 576, '노원구': 577, '구역': 578, '방법으로': 579, '무슨': 580, '허가를': 581, '원하는': 582, '폭': 583, '임기는': 584, '복지시설': 585, '서커스': 586, '최근': 587, '우리': 588, '개별': 589, '지역에': 590, '지역을': 591, '토지의': 592, '주민의': 593, '조회': 594, '경미한': 595, '대출': 596, '점검': 597, '범위는': 598, '지원대상': 599, '있는데': 600, '업무에': 601, '나': 602, '개발': 603, '개선': 604, '합니까': 605, '교통편': 606, '도보': 607, '홈페이지에': 608, '대해서는': 609, '부서': 610, '국가기술자격법에': 611, '확대': 612, '법률에': 613, '강서구': 614, '신청시': 615, '어디에서': 616, '문의시': 617, '가입': 618, '동의를': 619, '이하인': 620, '판매': 621, '정비': 622, '관계없이': 623, '공부방': 624, '이용요금': 625, '퍼센트': 626, '이상입니다': 627, '원칙적으로': 628, '년도': 629, '바닥면적의': 630, '동물': 631, '주민등록증': 632, '도시디자인': 633, '공모전': 634, '임신출산': 635, '장기기증': 636, '발표': 637, '일부': 638, '은': 639, '되며': 640, '여부를': 641, '신분증': 642, '기본': 643, '지정': 644, '공간': 645, '있으나': 646, '원칙으로': 647, '확인가능': 648, '도로로서': 649, '외의': 650, '부패행위': 651, '신고는': 652, '정보를': 653, '센터': 654, '내에': 655, '받는': 656, '지역사회': 657, '때문에': 658, '연계': 659, '서비스를': 660, '즉시': 661, '없으며': 662, '규칙': 663, '소유하고': 664, '각각': 665, '개최': 666, '길': 667, '무엇을': 668, '궁금합니다': 669, '시설로서': 670, '공원': 671, '분야별': 672, '구비서류는': 673, '절차를': 674, '여론조사': 675, '성북구': 676, '주는': 677, '상호': 678, '금전을': 679, '아니라': 680, '향상을': 681, '이란': 682, '해당하지': 683, '미리': 684, '건축허가': 685, '사전': 686, '대해서': 687, '제조제항에': 688, '외부강의': 689, '수상': 690, '이행기준': 691, '우편': 692, '길음동': 693, '제종근린생활시설': 694, '홍보': 695, '불법': 696, '이외의': 697, '운영에': 698, '직원': 699, '연중': 700, '종': 701, '이상이': 702, '특히': 703, '주택법': 704, '등록한': 705, '면적이': 706, '이용시간': 707, '자동차': 708, '제종': 709, '의무': 710, '구청에서': 711, '컴퓨터': 712, '접속': 713, '새로운': 714, '기관': 715, '하차': 716, '관련종목의': 717, '무료로': 718, '는': 719, '인정': 720, '제조제항': 721, '용도로': 722, '최종': 723, '차상위': 724, '설치할': 725, '담당': 726, '개인정보': 727, '환경': 728, '맞춤형': 729, '분야': 730, '시설의': 731, '사업자': 732, '건물': 733, '시설에': 734, '시행하는': 735, '확인서': 736, '발생하는': 737, '고려하여': 738, '공동주택에서': 739, '그러하지': 740, '민원을': 741, '적합한': 742, '아동': 743, '않을': 744, '구청장이': 745, '사업은': 746, '차상위계층': 747, '건물의': 748, '주의사항': 749, '별도로': 750, '하반기': 751, '제출서류': 752, '인재개발원': 753, '자격을': 754, '시군구': 755, '빈집': 756, '층평일': 757, '에너지': 758, '특정': 759, '접수방법': 760, '국토의': 761, '주로': 762, '제도': 763, '해야하나요': 764, '주민센터': 765, '것들이': 766, '건설기술관리법': 767, '우리구': 768, '휴무': 769, '담당자에게': 770, '컨설팅': 771, '등록이': 772, '민원': 773, '어디로': 774, '하시면': 775, '설치검사를': 776, '결과': 777, '일부를': 778, '방법이': 779, '이용방법': 780, '란': 781, '자녀': 782, '하기': 783, '일까지': 784, '입력': 785, '피해를': 786, '가까운': 787, '의료비': 788, '제외한': 789, '학생': 790, '기간': 791, '포함된': 792, '직장': 793, '꼭': 794, '관리하는': 795, '있다면': 796, '정하고': 797, '클릭': 798, '거주하는': 799, '주시면': 800, '종류': 801, '일시': 802, '소유자': 803, '근무': 804, '부분의': 805, '내용이': 806, '변경하는': 807, '활성화': 808, '수행하는': 809, '사용하는': 810, '동작구': 811, '성북동': 812, '원어민': 813, '새마을금고': 814, '임원의': 815, '동주민센터': 816, '도로의': 817, '건설하는': 818, '신고를': 819, '지정한': 820, '대상이': 821, '제출된': 822, '주말': 823, '없다고': 824, '국민건강보험공단': 825, '발생': 826, '통보': 827, '주요내용': 828, '지정된': 829, '참가자': 830, '공직자': 831, '발급받을': 832, '가능하나': 833, '사항에': 834, '방지하기': 835, '서류를': 836, '연간': 837, '응답소': 838, '자치구별': 839, '지원내용': 840, '높은': 841, '가능한지': 842, '시행규칙': 843, '규정한': 844, '왜': 845, '관계': 846, '되고': 847, '제출하시면': 848, '곳': 849, '하게': 850, '인터넷으로': 851, '일일': 852, '속하는': 853, '시민의': 854, '일부터': 855, '비용을': 856, '산정': 857, '사유로': 858, '전화번호는': 859, '있거나': 860, '동시에': 861, '일목': 862, '시설물': 863, '강북구': 864, '즉': 865, '관악구': 866, '변경이': 867, '수는': 868, '상반기': 869, '소': 870, '이상을': 871, '개인회생': 872, '제항에': 873, '지장이': 874, '강동구': 875, '조정': 876, '해당되는': 877, '신청은': 878, '근무시간': 879, '인정하는': 880, '가능하며': 881, '캠페인': 882, '운동': 883, '일토': 884, '자료': 885, '건강한': 886, '면적은': 887, '기업': 888, '사업에': 889, '그에': 890, '상': 891, '서울신용보증재단': 892, '참가': 893, '용적률': 894, '제작': 895, '사업종료': 896, '치': 897, '도시농업': 898, '당': 899, '순위': 900, '집회시설': 901, '대기환경보전법에': 902, '꽃': 903, '방과': 904, '영상': 905, '친환경': 906, '간': 907, '운영을': 908, '예비군': 909, '훈련': 910, '하나로': 911, '참고': 912, '예산': 913, '구성된': 914, '확인하여': 915, '규모는': 916, '대학생': 917, '어린이집에': 918, '호의': 919, '하나에': 920, '밀접한': 921, '알려주세요': 922, '등록된': 923, '어떤것이': 924, '관련한': 925, '사회적': 926, '하여금': 927, '문자': 928, '건축물대장의': 929, '이내의': 930, '주민': 931, '시장': 932, '게시물': 933, '우려가': 934, '영유아': 935, '육아종합지원센터': 936, '이하로': 937, '편의를': 938, '비용': 939, '여러': 940, '있어서': 941, '규정이': 942, '첨부': 943, '토목': 944, '기술자격취득자': 945, '자신의': 946, '삶의': 947, '저소득': 948, '수급자': 949, '초과하는': 950, '선정된': 951, '못한': 952, '거주지': 953, '날부터': 954, '분양': 955, '사람이': 956, '후원': 957, '제공하는': 958, '위원의': 959, '건축할': 960, '의하면': 961, '문자로': 962, '하단': 963, '지원에': 964, '조사': 965, '영향을': 966, '접수기간': 967, '어떠한': 968, '중에': 969, '인가를': 970, '드립니다': 971, '상담을': 972, '곳이': 973, '공동으로': 974, '법인': 975, '철거되는': 976, '제한': 977, '원활한': 978, '관리비': 979, '토': 980, '과태료': 981, '받으실': 982, '응모': 983, '도로를': 984, '사이트': 985, '전화로': 986, '하나': 987, '신청하시면': 988, '문서를': 989, '지참': 990, '인정하여': 991, '문화행사': 992, '백만원': 993, '지방공무원법': 994, '보상은': 995, '배정': 996, '아래': 997, '전액': 998, '활동': 999, '목': 1000, '강사': 1001, '온라인으로': 1002, '설립': 1003, '위해서는': 1004, '경제': 1005, '담은': 1006, '보다': 1007, '같음': 1008, '포함하여': 1009, '민원처리': 1010, '제출하면': 1011, '소규모': 1012, '인을': 1013, '기능을': 1014, '이용하는': 1015, '확보': 1016, '이용하시면': 1017, '기재': 1018, '아닙니다': 1019, '이용안내': 1020, '차량': 1021, '주거환경': 1022, '보호를': 1023, '서울시가': 1024, '와': 1025, '쉽게': 1026, '향후': 1027, '사무': 1028, '사용하지': 1029, '여성': 1030, '표창': 1031, '우수': 1032, '건설기술관리법에': 1033, '부과': 1034, '본': 1035, '개인이': 1036, '도시계획': 1037, '지원사업': 1038, '서울소재': 1039, '당일': 1040, '특례': 1041, '출산': 1042, '가구의': 1043, '최초': 1044, '어려운': 1045, '자는': 1046, '제외한다': 1047, '지': 1048, '폐지': 1049, '이수한': 1050, '금천구': 1051, '제출한': 1052, '것이며': 1053, '지방자치단체': 1054, '상단': 1055, '예시': 1056, '외에': 1057, '시행하고': 1058, '신청서를': 1059, '세입자': 1060, '보고': 1061, '일을': 1062, '이용한': 1063, '지역의': 1064, '증명서': 1065, '과반수의': 1066, '도시지역': 1067, '행위': 1068, '사진': 1069, '주택에': 1070, '아니하다': 1071, '주시기': 1072, '향상': 1073, '유형': 1074, '일정한': 1075, '문의는': 1076, '따로': 1077, '보일러': 1078, '미만의': 1079, '대통령령으로': 1080, '경우를': 1081, '소득': 1082, '주거지역': 1083, '것이다': 1084, '만들기': 1085, '위치한': 1086, '신청자격': 1087, '필요가': 1088, '발코니': 1089, '건축물에': 1090, '번호': 1091, '우리은행': 1092, '교복': 1093, '심사': 1094, '정당한': 1095, '동별': 1096, '제호에': 1097, '운영할': 1098, '동일한': 1099, '지방자치단체의': 1100, '질': 1101, '시스템인가요': 1102, '리모델링': 1103, '보조금': 1104, '가족': 1105, '시간연장': 1106, '안': 1107, '하나의': 1108, '우리동네': 1109, '과': 1110, '연중무휴': 1111, '무교동': 1112, '업무시설': 1113, '버스': 1114, '개정': 1115, '텃밭': 1116, '공장': 1117, '할인': 1118, '시까지': 1119, '영리를': 1120, '대지면적의': 1121, '건강가정지원센터': 1122, '싶어요': 1123, '메인화면': 1124, '있지만': 1125, '하거나': 1126, '모집기간': 1127, '화': 1128, '교수': 1129, '실시간': 1130, '안전한': 1131, '공지': 1132, '모니터링': 1133, '상황에': 1134, '부득이한': 1135, '바로': 1136, '추후': 1137, '신청자': 1138, '도시계획위원회': 1139, '과반수': 1140, '연': 1141, '납부': 1142, '한국': 1143, '일상감사': 1144, '승인': 1145, '공간을': 1146, '결과를': 1147, '월부터': 1148, '된다': 1149, '전용': 1150, '시청': 1151, '연결하는': 1152, '구청의': 1153, '가정': 1154, '목적': 1155, '확충': 1156, '지역별': 1157, '뭔가요': 1158, '명칭': 1159, '년에': 1160, '사본을': 1161, '설정': 1162, '이용가능': 1163, '승인을': 1164, '기존의': 1165, '자유롭게': 1166, '교육대상': 1167, '내외': 1168, '강화': 1169, '수가': 1170, '신청하는': 1171, '내지': 1172, '않도록': 1173, '년이상': 1174, '없으나': 1175, '수수료': 1176, '종합적인': 1177, '서울산업진흥원': 1178, '평균': 1179, '년이': 1180, '경우로서': 1181, '서울시교육청': 1182, '있어야': 1183, '추진위원회': 1184, '계약': 1185, '없도록': 1186, '이전에': 1187, '사용되는': 1188, '곳에': 1189, '인해': 1190, '성희롱': 1191, '용': 1192, '사업장': 1193, '제시': 1194, '외부': 1195, '전환': 1196, '되는지': 1197, '장': 1198, '커뮤니티': 1199, '서대문구에서는': 1200, '도움을': 1201, '신청할': 1202, '거주': 1203, '지자체': 1204, '지원하고': 1205, '지원이': 1206, '보수는': 1207, '범위안에서': 1208, '관리는': 1209, '안전사고': 1210, '중랑구': 1211, '권리를': 1212, '세부사업은': 1213, '영어회화': 1214, '중인': 1215, '수준': 1216, '통합': 1217, '안에': 1218, '아동의': 1219, '서울시에': 1220, '확인사항': 1221, '초과': 1222, '금지': 1223, '서식': 1224, '부당한': 1225, '다중주택': 1226, '월금': 1227, '대지': 1228, '요청': 1229, '전시': 1230, '의무가': 1231, '대상자가': 1232, '범위내에서': 1233, '시장이': 1234, '시설과': 1235, '소재지': 1236, '복지': 1237, '지점': 1238, '배출': 1239, '의료기관이': 1240, '해외': 1241, '경기도': 1242, '여행': 1243, '신청가능': 1244, '이루어': 1245, '창업': 1246, '과장': 1247, '이용대상': 1248, '금요일': 1249, '동의서': 1250, '가출': 1251, '대리인': 1252, '신청사': 1253, '공모': 1254, '누가': 1255, '수영장': 1256, '공관': 1257, '교육연구': 1258, '수질환경보전법에': 1259, '유스호스텔': 1260, '노력을': 1261, '작품': 1262, '상금': 1263, '공모대행제': 1264, '임신부': 1265, '건립': 1266, '지정되어': 1267, '시에서': 1268, '자격증': 1269, '수여': 1270, '교육일정': 1271, '제강': 1272, '지방자치': 1273, '입소': 1274, '받게': 1275, '시간을': 1276, '핸드폰': 1277, '사용자': 1278, '재산등록': 1279, '임원': 1280, '있을까요': 1281, '공간입니다': 1282, '정도': 1283, '안전관리': 1284, '점검사항은': 1285, '좋은가': 1286, '없나요': 1287, '점': 1288, '바람': 1289, '전자민원': 1290, '비밀번호': 1291, '약국을': 1292, '도': 1293, '금액을': 1294, '직무를': 1295, '제조제호의': 1296, '혹은': 1297, '데': 1298, '가능하도록': 1299, '시공': 1300, '신고하면': 1301, '건축과에서': 1302, '면': 1303, '발생시': 1304, '대한민국': 1305, '주민이': 1306, '예': 1307, '이름을': 1308, '문의사항': 1309, '과정을': 1310, '유사': 1311, '중에서': 1312, '이루어지는': 1313, '역할': 1314, '운영개요': 1315, '서면으로': 1316, '비용은': 1317, '동대문구': 1318, '가지': 1319, '법령을': 1320, '해당됩니다': 1321, '기계분야': 1322, '생활을': 1323, '실시하지': 1324, '동일하게': 1325, '영어': 1326, '의결을': 1327, '번출구에서': 1328, '명으로': 1329, '사업이': 1330, '정비사업': 1331, '조합': 1332, '납부하지': 1333, '자로서': 1334, '소정의': 1335, '없어': 1336, '없을': 1337, '말하는': 1338, '농협': 1339, '있으니': 1340, '있음을': 1341, '등록증': 1342, '시설로': 1343, '위원회는': 1344, '패널': 1345, '포인트': 1346, '청계천': 1347, '도시의': 1348, '설치하고': 1349, '접수처': 1350, '효율적으로': 1351, '회에': 1352, '구체적인': 1353, '성명': 1354, '설치하여': 1355, '공연': 1356, '대책': 1357, '활용할': 1358, '재산을': 1359, '배': 1360, '문의전화': 1361, '주민등록등본': 1362, '가족관계증명서': 1363, '아래의': 1364, '조합원의': 1365, '소요되는': 1366, '선임': 1367, '상담전화': 1368, '운동시설': 1369, '이용하여': 1370, '포함한다': 1371, '공사를': 1372, '대표전화': 1373, '법령': 1374, '하고자': 1375, '검사를': 1376, '받도록': 1377, '구로구': 1378, '오후': 1379, '가진': 1380, '계획은': 1381, '등에서': 1382, '사유가': 1383, '초': 1384, '규정된': 1385, '편리한': 1386, '설치기준은': 1387, '용역': 1388, '대중교통': 1389, '업체': 1390, '소유권을': 1391, '주소를': 1392, '위원회의': 1393, '지하수': 1394, '보행자': 1395, '한해': 1396, '규모': 1397, '단지': 1398, '따르면': 1399, '공급': 1400, '일단의': 1401, '송파': 1402, '관리에': 1403, '물품의': 1404, '않으면': 1405, '보육': 1406, '저작권': 1407, '상장': 1408, '수요일': 1409, '시도': 1410, '주민등록': 1411, '신고해야': 1412, '방향으로': 1413, '해당되지': 1414, '관리처분계획을': 1415, '서울시에서는': 1416, '대표번호': 1417, '감사를': 1418, '종료': 1419, '되나요건설기술관리법에': 1420, '천세대': 1421, '이미': 1422, '확인이': 1423, '임대주택을': 1424, '아닌가요': 1425, '가장': 1426, '단속': 1427, '필수': 1428, '근로자': 1429, '활용하여': 1430, '증빙서류': 1431, '요금': 1432, '외국인주민': 1433, '숙박시설': 1434, '직무관련자가': 1435, '다가구주택': 1436, '위험물저장': 1437, '이야기': 1438, '제외되는': 1439, 'ㅁ': 1440, '상담이': 1441, '영업점': 1442, '은평': 1443, '제조구매': 1444, '서울특별시육아종합지원센터': 1445, '가입자': 1446, '예체능': 1447, '지그재그': 1448, '해당한다': 1449, '개월마다': 1450, '아님': 1451, '있으면': 1452, '자원봉사': 1453, '모바일': 1454, '교육내용': 1455, '대표': 1456, '평가': 1457, '초등학생': 1458, '개발행위허가': 1459, '조사를': 1460, '불구하고': 1461, '지방자치단체가': 1462, '타기관': 1463, '않으며': 1464, '년부터': 1465, '신청하면': 1466, '입주자대표회의': 1467, '구의원': 1468, '감사': 1469, '디자인입니다': 1470, '기능': 1471, '건설공사': 1472, '지하': 1473, '현장': 1474, '제도입니다': 1475, '회원가입': 1476, '분실': 1477, '명단': 1478, '역': 1479, '잘': 1480, '관심을': 1481, '경우도': 1482, '처리하는': 1483, '시민들의': 1484, '유지': 1485, '사업내용': 1486, '협회': 1487, '구청에': 1488, '라': 1489, '물론': 1490, '적극': 1491, '홍보물': 1492, '유도': 1493, '방지': 1494, '알려드립니다': 1495, '원하시는': 1496, '직무상': 1497, '함께하는': 1498, '대여': 1499, '해당합니다': 1500, '월일': 1501, '자녀를': 1502, '앱': 1503, '개인의': 1504, '세대를': 1505, '이후에': 1506, '교육생': 1507, '일자리': 1508, '국내': 1509, '최초로': 1510, '청원': 1511, '하지만': 1512, '민원인이': 1513, '자녀와': 1514, '교육비': 1515, '도시계획시설': 1516, '여성의': 1517, '관련이': 1518, '소통의': 1519, '전문': 1520, '수련원': 1521, '직무': 1522, '기관별': 1523, '의료급여를': 1524, '얼마인가요': 1525, '부동산정보': 1526, '건': 1527, '예산을': 1528, '발생한': 1529, '면적의': 1530, '업무가': 1531, '발생할': 1532, '시민청': 1533, '가구': 1534, '못하는': 1535, '단독주택': 1536, '제조제항의': 1537, '실제': 1538, '문자표출용': 1539, '방향': 1540, '현': 1541, '제한하고': 1542, '보아야': 1543, '도서관': 1544, '구청장': 1545, '활성화를': 1546, '피해자': 1547, '지원센터': 1548, '가정폭력': 1549, '가능한지요': 1550, '경우가': 1551, '날로부터': 1552, '스스로': 1553, '회의실': 1554, '주거환경정비법': 1555, '하도록': 1556, '구조': 1557, '새로': 1558, '거리를': 1559, '체계적으로': 1560, '올림픽로': 1561, '형태로': 1562, '메인': 1563, '과도한': 1564, '위의': 1565, '계산': 1566, '만세': 1567, '조합임원의': 1568, '면적을': 1569, '날을': 1570, '필요한가요': 1571, '구체적으로': 1572, '확정': 1573, '행하는': 1574, '명이': 1575, '불가합니다': 1576, '확보를': 1577, '정한다': 1578, '국번없이': 1579, '보육시설': 1580, '우선적으로': 1581, '양천구': 1582, '자에': 1583, '현황을': 1584, '안에서': 1585, '수립하여야': 1586, '하므로': 1587, '분양신청을': 1588, '도정법': 1589, '민원서류': 1590, '이상으로': 1591, '맞추어': 1592, '공사에': 1593, '상속인': 1594, '돈암동': 1595, '목의': 1596, '일정기간': 1597, '자동차관련시설': 1598, '건축이': 1599, '영업시설': 1600, '소재한': 1601, '올바른': 1602, '참고로': 1603, '공개': 1604, '원칙': 1605, '직원의': 1606, '확정된': 1607, '매': 1608, '사업시행자가': 1609, '관리규약에': 1610, '것이므로': 1611, '계약심사': 1612, '글로벌': 1613, '관련하여': 1614, '자를': 1615, '설치기준': 1616, '서울에서': 1617, '공동': 1618, '부문': 1619, '도입': 1620, '안됩니다': 1621, '근로자의': 1622, '한다고': 1623, '보육교사': 1624, '창동': 1625, '행정서비스': 1626, '실습': 1627, '기관의': 1628, '교부': 1629, '부모': 1630, '회원가입을': 1631, '제출하여야': 1632, '갖춘': 1633, '기간은': 1634, '임대': 1635, '여부는': 1636, '지정공고한': 1637, '제가': 1638, '준': 1

word_counts 속성으로 단어와 빈도수가 묶인 튜플을 얻어온다.

In [129]:
list(tokenizer.word_counts.items())[:10]

[('우리아이의', 2),
 ('배정', 11),
 ('초등학교를', 2),
 ('알고', 45),
 ('싶어요', 10),
 ('싶어요매년', 1),
 ('취학통지서', 1),
 ('발급', 66),
 ('때가', 1),
 ('되면', 7)]

단어별 빈도를 고빈도순으로 정렬한다.

In [138]:
word_df = pd.DataFrame(tokenizer.word_counts.items(), columns=['단어', '빈도수']).set_index('단어')
word_df.sort_values(by='빈도수', ascending=False).T

단어,및,돋움,수,경우,또는,등,있는,년,있습니다,월,...,굴착면,제거하였느가,안전히,부석은,발파후,낙석방지,옵니다,통보가,통학구역이,때가
빈도수,1455,1110,771,595,550,547,411,400,379,379,...,1,1,1,1,1,1,1,1,1,1

texts_to_sequences() 메소드로 fit_on_texts() 메소드가 벡터화한 정보에서 찾아서 문장을 숫자로 표현한 리스트로 만든다.

In [142]:
train_sequence = tokenizer.texts_to_sequences(x_train)
test_sequence = tokenizer.texts_to_sequences(x_test)

## 패딩하기

자연어 처리를 하다 보면 각 문장 또는 문서의 길이가 서로 다를 수 있다. 컴퓨터는 문서의 길이가 같아야만 하나의 행렬로 보고 한꺼번에 묶어서 처리할 수 있으므로, 병렬 연산을 위해서는 여러 문장의 길이를 동일하게 맞추는 작업이 필요하다.

<img src="./패딩적용.png" width="600" align="left" />

실제 데이터에 패딩을 적용해 독립 변수를 전처리해서 문장의 길이가 제각각인 벡터의 크기를 패딩 작업으로 나머지 빈 공간을 0으로 채워준다.

데이터에 패딩을 적용하기 위해 pad_sequences를 import 한다.

In [144]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

pad_sequences() 메소드의 `첫 번째 인수`는 texts_to_sequences() 메소드로 만든 문장을 숫자로 표현한 리스트를 넘겨준다.  
`padding` 속성의 기본값은 'pre'이고 패딩을 시퀀스의 앞쪽에 패딩을 채우고 'post'는 시퀀스의 뒤쪽에 패딩을 채운다.  
`maxlen` 속성은 시퀀스의 최대 길이를 지정한다.

In [150]:
max_length = 500
x_train_sp = pad_sequences(train_sequence, padding='post', maxlen=max_length)
x_test_sp = pad_sequences(test_sequence, padding='post', maxlen=max_length)
print(x_train_sp.shape, x_test_sp.shape)

(1710, 500) (428, 500)

# 모델 만들기

Sequential: 신경망 모델을 구축하기 위해서 레이어를 선형으로 차례차례 쌓는 순차적 모델 구조를 만든다.  
Dense: 모든 입력 뉴런과 출력 뉴런 서로 연결된 완전 연결 레이어로 모델의 최종 출력이나 일반적인 연산에 사용된다.  
Embedding: 텍스트 데이터를 수치형 벡터로 변환하는 임베딩 레이어로 단어 사이의 유사도를 학습하여 고차원의 희소 백터를 저차원의 밀집 벡터로 압축한다.  
Bidirectional: RNN 계열에 적용되며, 데이터를 정방향과 역방향 모드에서 처리하도록 감싸주는 wrapper로 문맥의 앞뒤를 모두 파악해야 하는 자연여 처리에서 성능이 좋다.  
LSTM: RNN의 일종으로, 장기 의존성 문제(긴 시퀀스에서 초기 정보를 잊어버리는 문제)를 해결하기 위해 설계된 레이어로 시계열 데이터나 텍스트 처리에 성능이 좋다.  
Dropout: 학습 시 무작위로 일부 뉴런 끔으로써 과적합을 방지하는 규제 기법이다.  
BatchNormalization: 각 레이어의 출력을 평균을 0, 표준편차가 1이 되도록 정규화하여 정규화하여 학습 속도를 높이고 안정성을 더해준다.

In [151]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Embedding, Bidirectional, LSTM, Dropout, BatchNormalization

In [162]:
n_class = y_train.shape[1]
n_class

3

## Bidirectional LSTM

전방향 후방향을 모두 사용하는 양방향 RNN에 LSTM 셀을 가진 모델을 다룬다. RNN이 연쇄된 문장을 다루는 데 유능하지만, 연쇄가 매우 길어질 때는 기울기 소실 문제가 생긴다. 이로 인해 필요한 정보를 멀리까지 보낼 수 있는 방안으로 LSTM이 고안됐다.

단어의 연쇄로 이루어진 데이터가 임베딩 레이어를 거치게 되는데 max_length는 한 문장의 최대 단어 길이로 패딩의 기준이 된다. Bidirectional LSTM의 첫 번째 층은 연쇄로 이루어져 있기 때문에 return_sequences=True로 설정한다.

In [165]:
# 모델 정의 시작: 레이어를 순서대로 하나씩 쌓는 순차적 모델 구조를 생성한다.
model = Sequential([
    # 단어 벡터화 층: 숫자로 변환된 단어 인덱스를 의미를 가지는 밀집 벡터(dence vector)로 바꾼다.
    # input_dim: 단어 사전의 크기
    # output_dim: 단어를 표현할 벡터의 크기(차원)
    # input_shape: 입력되는 문장의 최대 단어 수
    Embedding(input_dim=vocab_size, output_dim=64, input_shape=(max_length,)),
    # 첫 번째 양방향 LSTM 층
    # Bidirectional: 문장을 왼쪽에서 오른쪽으로(정방향), 오른쪽에서 왼쪽으로(역방향) 두 번 읽어 문맥을 양방향에서 파악한다.
    # units: 64개의 유닛을 가진 LSTM 층이다. 긴 문장에서 앞부분의 정보를 끝까지 잘 전달한다.
    # return_sequences=True: 중요한 설정이다. 다음 층도 LSTM이므로, 모든 시점의 출력을 넘겨 연속적인 시퀀스 학습이 가능케 한다.
    Bidirectional(LSTM(units=64, return_sequences=True)),
    # 배치 정규화 층
    # 이전 층의 출력값을 정규하하여 학습 속도를 높이고, 가중치 초기화에 대한 민감도를 줄여 모델을 안정화한다.
    BatchNormalization(),
    # 두 번째 양방향 LSTM 층
    # units: 유닛 개수를 32개로 줄여 정보를 압축한다.
    # return_sequences=True가 없다. 즉, 전체 문장을 다 읽은 후의 최종 요약된 정보만 다음층으로 전달한다.
    Bidirectional(LSTM(units=32)),
    # 학습 시 무작위로 뉴런 20%를 끈다. 특정 뉴런에 과도하게 의존하는 것을 방지하여 과적합을 예방한다.
    Dropout(0.2),
    # 완전 연결 및 출력 층
    # 추출된 특징들을 바탕으로 학습하는 일반적인 신경망 층이다. relu 활성화 함수를 사용해서 비선형성을 추가한다.
    Dense(units=16, activation='relu'),
    # 최종 출력 층: n_class는 분류하려는 카테고리 개수이다.
    # softmax: 출력값을 확류(0 ~ 1 사이, 총합 1)로 변환한다. 가장 높은 확율을 가진 클래스를 최종 예측값으로 선택하게 된다.
    Dense(units=n_class, activation='softmax')
])
# model.summary()